/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.EvolutionTriggersRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class EvolutionTriggers extends TableImpl<EvolutionTriggersRecord> {

    /**
     * The reference instance of {@code evolution_triggers}
     */
    public static final EvolutionTriggers EVOLUTION_TRIGGERS = new EvolutionTriggers();
    private static final long serialVersionUID = 786607672;
    /**
     * The column {@code evolution_triggers.id}.
     */
    public final TableField<EvolutionTriggersRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code evolution_triggers.identifier}.
     */
    public final TableField<EvolutionTriggersRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");

    /**
     * Create a {@code evolution_triggers} table reference
     */
    public EvolutionTriggers() {
        this("evolution_triggers", null);
    }

    private EvolutionTriggers(String alias, Table<EvolutionTriggersRecord> aliased) {
        this(alias, aliased, null);
    }

    private EvolutionTriggers(String alias, Table<EvolutionTriggersRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code evolution_triggers} table reference
     */
    public EvolutionTriggers(String alias) {
        this(alias, EVOLUTION_TRIGGERS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EvolutionTriggersRecord> getPrimaryKey() {
        return Keys.PK_EVOLUTION_TRIGGERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EvolutionTriggersRecord>> getKeys() {
        return Arrays.<UniqueKey<EvolutionTriggersRecord>>asList(Keys.PK_EVOLUTION_TRIGGERS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvolutionTriggers as(String alias) {
        return new EvolutionTriggers(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EvolutionTriggersRecord> getRecordType() {
        return EvolutionTriggersRecord.class;
    }

    /**
     * Rename this table
     */
    public EvolutionTriggers rename(String name) {
        return new EvolutionTriggers(name, null);
    }
}
