/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.GendersRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class Genders extends TableImpl<GendersRecord> {

    /**
     * The reference instance of {@code genders}
     */
    public static final Genders GENDERS = new Genders();
    private static final long serialVersionUID = 38496238;
    /**
     * The column {@code genders.id}.
     */
    public final TableField<GendersRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code genders.identifier}.
     */
    public final TableField<GendersRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");

    /**
     * Create a {@code genders} table reference
     */
    public Genders() {
        this("genders", null);
    }

    private Genders(String alias, Table<GendersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Genders(String alias, Table<GendersRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code genders} table reference
     */
    public Genders(String alias) {
        this(alias, GENDERS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GendersRecord> getPrimaryKey() {
        return Keys.PK_GENDERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GendersRecord>> getKeys() {
        return Arrays.<UniqueKey<GendersRecord>>asList(Keys.PK_GENDERS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Genders as(String alias) {
        return new Genders(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GendersRecord> getRecordType() {
        return GendersRecord.class;
    }

    /**
     * Rename this table
     */
    public Genders rename(String name) {
        return new Genders(name, null);
    }
}
