/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.GenerationNamesRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class GenerationNames extends TableImpl<GenerationNamesRecord> {

    /**
     * The reference instance of {@code generation_names}
     */
    public static final GenerationNames GENERATION_NAMES = new GenerationNames();
    private static final long serialVersionUID = -24387735;
    /**
     * The column {@code generation_names.generation_id}.
     */
    public final TableField<GenerationNamesRecord, Integer> GENERATION_ID =
            createField("generation_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code generation_names.local_language_id}.
     */
    public final TableField<GenerationNamesRecord, Integer> LOCAL_LANGUAGE_ID =
            createField("local_language_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code generation_names.name}.
     */
    public final TableField<GenerationNamesRecord, String> NAME =
            createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");

    /**
     * Create a {@code generation_names} table reference
     */
    public GenerationNames() {
        this("generation_names", null);
    }

    private GenerationNames(String alias, Table<GenerationNamesRecord> aliased) {
        this(alias, aliased, null);
    }

    private GenerationNames(String alias, Table<GenerationNamesRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code generation_names} table reference
     */
    public GenerationNames(String alias) {
        this(alias, GENERATION_NAMES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GenerationNamesRecord> getPrimaryKey() {
        return Keys.PK_GENERATION_NAMES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GenerationNamesRecord>> getKeys() {
        return Arrays.<UniqueKey<GenerationNamesRecord>>asList(Keys.PK_GENERATION_NAMES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GenerationNamesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GenerationNamesRecord, ?>>asList(Keys.FK_GENERATION_NAMES_GENERATIONS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenerationNames as(String alias) {
        return new GenerationNames(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GenerationNamesRecord> getRecordType() {
        return GenerationNamesRecord.class;
    }

    /**
     * Rename this table
     */
    public GenerationNames rename(String name) {
        return new GenerationNames(name, null);
    }
}
