/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.GenerationsRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class Generations extends TableImpl<GenerationsRecord> {

    /**
     * The reference instance of {@code generations}
     */
    public static final Generations GENERATIONS = new Generations();
    private static final long serialVersionUID = -1988029207;
    /**
     * The column {@code generations.id}.
     */
    public final TableField<GenerationsRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code generations.main_region_id}.
     */
    public final TableField<GenerationsRecord, Integer> MAIN_REGION_ID =
            createField("main_region_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code generations.identifier}.
     */
    public final TableField<GenerationsRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");

    /**
     * Create a {@code generations} table reference
     */
    public Generations() {
        this("generations", null);
    }

    private Generations(String alias, Table<GenerationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Generations(String alias, Table<GenerationsRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code generations} table reference
     */
    public Generations(String alias) {
        this(alias, GENERATIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GenerationsRecord> getPrimaryKey() {
        return Keys.PK_GENERATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GenerationsRecord>> getKeys() {
        return Arrays.<UniqueKey<GenerationsRecord>>asList(Keys.PK_GENERATIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GenerationsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GenerationsRecord, ?>>asList(Keys.FK_GENERATIONS_REGIONS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Generations as(String alias) {
        return new Generations(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GenerationsRecord> getRecordType() {
        return GenerationsRecord.class;
    }

    /**
     * Rename this table
     */
    public Generations rename(String name) {
        return new Generations(name, null);
    }
}
