/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.GrowthRatesRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class GrowthRates extends TableImpl<GrowthRatesRecord> {

    /**
     * The reference instance of {@code growth_rates}
     */
    public static final GrowthRates GROWTH_RATES = new GrowthRates();
    private static final long serialVersionUID = 1338018967;
    /**
     * The column {@code growth_rates.id}.
     */
    public final TableField<GrowthRatesRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code growth_rates.identifier}.
     */
    public final TableField<GrowthRatesRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");
    /**
     * The column {@code growth_rates.formula}.
     */
    public final TableField<GrowthRatesRecord, String> FORMULA =
            createField("formula", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a {@code growth_rates} table reference
     */
    public GrowthRates() {
        this("growth_rates", null);
    }

    private GrowthRates(String alias, Table<GrowthRatesRecord> aliased) {
        this(alias, aliased, null);
    }

    private GrowthRates(String alias, Table<GrowthRatesRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code growth_rates} table reference
     */
    public GrowthRates(String alias) {
        this(alias, GROWTH_RATES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GrowthRatesRecord> getPrimaryKey() {
        return Keys.PK_GROWTH_RATES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GrowthRatesRecord>> getKeys() {
        return Arrays.<UniqueKey<GrowthRatesRecord>>asList(Keys.PK_GROWTH_RATES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GrowthRates as(String alias) {
        return new GrowthRates(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GrowthRatesRecord> getRecordType() {
        return GrowthRatesRecord.class;
    }

    /**
     * Rename this table
     */
    public GrowthRates rename(String name) {
        return new GrowthRates(name, null);
    }
}
