/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.GrowthRateProseRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class GrowthRateProse extends TableImpl<GrowthRateProseRecord> {

    /**
     * The reference instance of {@code growth_rate_prose}
     */
    public static final GrowthRateProse GROWTH_RATE_PROSE = new GrowthRateProse();
    private static final long serialVersionUID = -67534807;
    /**
     * The column {@code growth_rate_prose.growth_rate_id}.
     */
    public final TableField<GrowthRateProseRecord, Integer> GROWTH_RATE_ID =
            createField("growth_rate_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code growth_rate_prose.local_language_id}.
     */
    public final TableField<GrowthRateProseRecord, Integer> LOCAL_LANGUAGE_ID =
            createField("local_language_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code growth_rate_prose.name}.
     */
    public final TableField<GrowthRateProseRecord, String> NAME =
            createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");

    /**
     * Create a {@code growth_rate_prose} table reference
     */
    public GrowthRateProse() {
        this("growth_rate_prose", null);
    }

    private GrowthRateProse(String alias, Table<GrowthRateProseRecord> aliased) {
        this(alias, aliased, null);
    }

    private GrowthRateProse(String alias, Table<GrowthRateProseRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code growth_rate_prose} table reference
     */
    public GrowthRateProse(String alias) {
        this(alias, GROWTH_RATE_PROSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GrowthRateProseRecord> getPrimaryKey() {
        return Keys.PK_GROWTH_RATE_PROSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GrowthRateProseRecord>> getKeys() {
        return Arrays.<UniqueKey<GrowthRateProseRecord>>asList(Keys.PK_GROWTH_RATE_PROSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GrowthRateProseRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GrowthRateProseRecord, ?>>asList(Keys.FK_GROWTH_RATE_PROSE_GROWTH_RATES_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GrowthRateProse as(String alias) {
        return new GrowthRateProse(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GrowthRateProseRecord> getRecordType() {
        return GrowthRateProseRecord.class;
    }

    /**
     * Rename this table
     */
    public GrowthRateProse rename(String name) {
        return new GrowthRateProse(name, null);
    }
}
