/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.ItemFlagProseRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class ItemFlagProse extends TableImpl<ItemFlagProseRecord> {

    /**
     * The reference instance of {@code item_flag_prose}
     */
    public static final ItemFlagProse ITEM_FLAG_PROSE = new ItemFlagProse();
    private static final long serialVersionUID = 1820299999;
    /**
     * The column {@code item_flag_prose.item_flag_id}.
     */
    public final TableField<ItemFlagProseRecord, Integer> ITEM_FLAG_ID =
            createField("item_flag_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code item_flag_prose.local_language_id}.
     */
    public final TableField<ItemFlagProseRecord, Integer> LOCAL_LANGUAGE_ID =
            createField("local_language_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code item_flag_prose.name}.
     */
    public final TableField<ItemFlagProseRecord, String> NAME =
            createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(79), this, "");
    /**
     * The column {@code item_flag_prose.description}.
     */
    public final TableField<ItemFlagProseRecord, String> DESCRIPTION =
            createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a {@code item_flag_prose} table reference
     */
    public ItemFlagProse() {
        this("item_flag_prose", null);
    }

    private ItemFlagProse(String alias, Table<ItemFlagProseRecord> aliased) {
        this(alias, aliased, null);
    }

    private ItemFlagProse(String alias, Table<ItemFlagProseRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code item_flag_prose} table reference
     */
    public ItemFlagProse(String alias) {
        this(alias, ITEM_FLAG_PROSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ItemFlagProseRecord> getPrimaryKey() {
        return Keys.PK_ITEM_FLAG_PROSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ItemFlagProseRecord>> getKeys() {
        return Arrays.<UniqueKey<ItemFlagProseRecord>>asList(Keys.PK_ITEM_FLAG_PROSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ItemFlagProseRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ItemFlagProseRecord, ?>>asList(Keys.FK_ITEM_FLAG_PROSE_ITEM_FLAGS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemFlagProse as(String alias) {
        return new ItemFlagProse(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemFlagProseRecord> getRecordType() {
        return ItemFlagProseRecord.class;
    }

    /**
     * Rename this table
     */
    public ItemFlagProse rename(String name) {
        return new ItemFlagProse(name, null);
    }
}
