/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.ItemCategoriesRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class ItemCategories extends TableImpl<ItemCategoriesRecord> {

    /**
     * The reference instance of {@code item_categories}
     */
    public static final ItemCategories ITEM_CATEGORIES = new ItemCategories();
    private static final long serialVersionUID = 687561911;
    /**
     * The column {@code item_categories.id}.
     */
    public final TableField<ItemCategoriesRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code item_categories.pocket_id}.
     */
    public final TableField<ItemCategoriesRecord, Integer> POCKET_ID =
            createField("pocket_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code item_categories.identifier}.
     */
    public final TableField<ItemCategoriesRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");

    /**
     * Create a {@code item_categories} table reference
     */
    public ItemCategories() {
        this("item_categories", null);
    }

    private ItemCategories(String alias, Table<ItemCategoriesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ItemCategories(String alias, Table<ItemCategoriesRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code item_categories} table reference
     */
    public ItemCategories(String alias) {
        this(alias, ITEM_CATEGORIES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ItemCategoriesRecord> getPrimaryKey() {
        return Keys.PK_ITEM_CATEGORIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ItemCategoriesRecord>> getKeys() {
        return Arrays.<UniqueKey<ItemCategoriesRecord>>asList(Keys.PK_ITEM_CATEGORIES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ItemCategoriesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ItemCategoriesRecord, ?>>asList(Keys.FK_ITEM_CATEGORIES_ITEM_POCKETS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemCategories as(String alias) {
        return new ItemCategories(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemCategoriesRecord> getRecordType() {
        return ItemCategoriesRecord.class;
    }

    /**
     * Rename this table
     */
    public ItemCategories rename(String name) {
        return new ItemCategories(name, null);
    }
}
