/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.ItemGameIndicesRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class ItemGameIndices extends TableImpl<ItemGameIndicesRecord> {

    /**
     * The reference instance of {@code item_game_indices}
     */
    public static final ItemGameIndices ITEM_GAME_INDICES = new ItemGameIndices();
    private static final long serialVersionUID = 1382748282;
    /**
     * The column {@code item_game_indices.item_id}.
     */
    public final TableField<ItemGameIndicesRecord, Integer> ITEM_ID =
            createField("item_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code item_game_indices.generation_id}.
     */
    public final TableField<ItemGameIndicesRecord, Integer> GENERATION_ID =
            createField("generation_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code item_game_indices.game_index}.
     */
    public final TableField<ItemGameIndicesRecord, Integer> GAME_INDEX =
            createField("game_index", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a {@code item_game_indices} table reference
     */
    public ItemGameIndices() {
        this("item_game_indices", null);
    }

    private ItemGameIndices(String alias, Table<ItemGameIndicesRecord> aliased) {
        this(alias, aliased, null);
    }

    private ItemGameIndices(String alias, Table<ItemGameIndicesRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code item_game_indices} table reference
     */
    public ItemGameIndices(String alias) {
        this(alias, ITEM_GAME_INDICES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ItemGameIndicesRecord> getPrimaryKey() {
        return Keys.PK_ITEM_GAME_INDICES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ItemGameIndicesRecord>> getKeys() {
        return Arrays.<UniqueKey<ItemGameIndicesRecord>>asList(Keys.PK_ITEM_GAME_INDICES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ItemGameIndicesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ItemGameIndicesRecord, ?>>asList(Keys.FK_ITEM_GAME_INDICES_ITEMS_1,
                                                                   Keys.FK_ITEM_GAME_INDICES_GENERATIONS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemGameIndices as(String alias) {
        return new ItemGameIndices(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemGameIndicesRecord> getRecordType() {
        return ItemGameIndicesRecord.class;
    }

    /**
     * Rename this table
     */
    public ItemGameIndices rename(String name) {
        return new ItemGameIndices(name, null);
    }
}
