/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.ItemFlagsRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class ItemFlags extends TableImpl<ItemFlagsRecord> {

    /**
     * The reference instance of {@code item_flags}
     */
    public static final ItemFlags ITEM_FLAGS = new ItemFlags();
    private static final long serialVersionUID = 1959441916;
    /**
     * The column {@code item_flags.id}.
     */
    public final TableField<ItemFlagsRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code item_flags.identifier}.
     */
    public final TableField<ItemFlagsRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");

    /**
     * Create a {@code item_flags} table reference
     */
    public ItemFlags() {
        this("item_flags", null);
    }

    private ItemFlags(String alias, Table<ItemFlagsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ItemFlags(String alias, Table<ItemFlagsRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code item_flags} table reference
     */
    public ItemFlags(String alias) {
        this(alias, ITEM_FLAGS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ItemFlagsRecord> getPrimaryKey() {
        return Keys.PK_ITEM_FLAGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ItemFlagsRecord>> getKeys() {
        return Arrays.<UniqueKey<ItemFlagsRecord>>asList(Keys.PK_ITEM_FLAGS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemFlags as(String alias) {
        return new ItemFlags(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemFlagsRecord> getRecordType() {
        return ItemFlagsRecord.class;
    }

    /**
     * Rename this table
     */
    public ItemFlags rename(String name) {
        return new ItemFlags(name, null);
    }
}
