/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.MoveFlavorTextRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MoveFlavorText extends TableImpl<MoveFlavorTextRecord> {

    /**
     * The reference instance of {@code move_flavor_text}
     */
    public static final MoveFlavorText MOVE_FLAVOR_TEXT = new MoveFlavorText();
    private static final long serialVersionUID = -1124317231;
    /**
     * The column {@code move_flavor_text.move_id}.
     */
    public final TableField<MoveFlavorTextRecord, Integer> MOVE_ID =
            createField("move_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_flavor_text.version_group_id}.
     */
    public final TableField<MoveFlavorTextRecord, Integer> VERSION_GROUP_ID =
            createField("version_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_flavor_text.language_id}.
     */
    public final TableField<MoveFlavorTextRecord, Integer> LANGUAGE_ID =
            createField("language_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_flavor_text.flavor_text}.
     */
    public final TableField<MoveFlavorTextRecord, String> FLAVOR_TEXT =
            createField("flavor_text", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a {@code move_flavor_text} table reference
     */
    public MoveFlavorText() {
        this("move_flavor_text", null);
    }

    private MoveFlavorText(String alias, Table<MoveFlavorTextRecord> aliased) {
        this(alias, aliased, null);
    }

    private MoveFlavorText(String alias, Table<MoveFlavorTextRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code move_flavor_text} table reference
     */
    public MoveFlavorText(String alias) {
        this(alias, MOVE_FLAVOR_TEXT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MoveFlavorTextRecord> getPrimaryKey() {
        return Keys.PK_MOVE_FLAVOR_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MoveFlavorTextRecord>> getKeys() {
        return Arrays.<UniqueKey<MoveFlavorTextRecord>>asList(Keys.PK_MOVE_FLAVOR_TEXT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MoveFlavorTextRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MoveFlavorTextRecord, ?>>asList(Keys.FK_MOVE_FLAVOR_TEXT_MOVES_1,
                                                                  Keys.FK_MOVE_FLAVOR_TEXT_VERSION_GROUPS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveFlavorText as(String alias) {
        return new MoveFlavorText(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MoveFlavorTextRecord> getRecordType() {
        return MoveFlavorTextRecord.class;
    }

    /**
     * Rename this table
     */
    public MoveFlavorText rename(String name) {
        return new MoveFlavorText(name, null);
    }
}
