/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.MoveMetaRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MoveMeta extends TableImpl<MoveMetaRecord> {

    /**
     * The reference instance of {@code move_meta}
     */
    public static final MoveMeta MOVE_META = new MoveMeta();
    private static final long serialVersionUID = -238473428;
    /**
     * The column {@code move_meta.move_id}.
     */
    public final TableField<MoveMetaRecord, Integer> MOVE_ID =
            createField("move_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_meta.meta_category_id}.
     */
    public final TableField<MoveMetaRecord, Integer> META_CATEGORY_ID =
            createField("meta_category_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_meta.meta_ailment_id}.
     */
    public final TableField<MoveMetaRecord, Integer> META_AILMENT_ID =
            createField("meta_ailment_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_meta.min_hits}.
     */
    public final TableField<MoveMetaRecord, Integer> MIN_HITS =
            createField("min_hits", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code move_meta.max_hits}.
     */
    public final TableField<MoveMetaRecord, Integer> MAX_HITS =
            createField("max_hits", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code move_meta.min_turns}.
     */
    public final TableField<MoveMetaRecord, Integer> MIN_TURNS =
            createField("min_turns", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code move_meta.max_turns}.
     */
    public final TableField<MoveMetaRecord, Integer> MAX_TURNS =
            createField("max_turns", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code move_meta.drain}.
     */
    public final TableField<MoveMetaRecord, Integer> DRAIN =
            createField("drain", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_meta.healing}.
     */
    public final TableField<MoveMetaRecord, Integer> HEALING =
            createField("healing", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_meta.crit_rate}.
     */
    public final TableField<MoveMetaRecord, Integer> CRIT_RATE =
            createField("crit_rate", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_meta.ailment_chance}.
     */
    public final TableField<MoveMetaRecord, Integer> AILMENT_CHANCE =
            createField("ailment_chance", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_meta.flinch_chance}.
     */
    public final TableField<MoveMetaRecord, Integer> FLINCH_CHANCE =
            createField("flinch_chance", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_meta.stat_chance}.
     */
    public final TableField<MoveMetaRecord, Integer> STAT_CHANCE =
            createField("stat_chance", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a {@code move_meta} table reference
     */
    public MoveMeta() {
        this("move_meta", null);
    }

    private MoveMeta(String alias, Table<MoveMetaRecord> aliased) {
        this(alias, aliased, null);
    }

    private MoveMeta(String alias, Table<MoveMetaRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code move_meta} table reference
     */
    public MoveMeta(String alias) {
        this(alias, MOVE_META);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MoveMetaRecord> getPrimaryKey() {
        return Keys.PK_MOVE_META;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MoveMetaRecord>> getKeys() {
        return Arrays.<UniqueKey<MoveMetaRecord>>asList(Keys.PK_MOVE_META);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MoveMetaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MoveMetaRecord, ?>>asList(Keys.FK_MOVE_META_MOVES_1,
                                                            Keys.FK_MOVE_META_MOVE_META_CATEGORIES_1,
                                                            Keys.FK_MOVE_META_MOVE_META_AILMENTS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMeta as(String alias) {
        return new MoveMeta(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MoveMetaRecord> getRecordType() {
        return MoveMetaRecord.class;
    }

    /**
     * Rename this table
     */
    public MoveMeta rename(String name) {
        return new MoveMeta(name, null);
    }
}
