/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.MoveMetaAilmentsRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MoveMetaAilments extends TableImpl<MoveMetaAilmentsRecord> {

    /**
     * The reference instance of {@code move_meta_ailments}
     */
    public static final MoveMetaAilments MOVE_META_AILMENTS = new MoveMetaAilments();
    private static final long serialVersionUID = 912058674;
    /**
     * The column {@code move_meta_ailments.id}.
     */
    public final TableField<MoveMetaAilmentsRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_meta_ailments.identifier}.
     */
    public final TableField<MoveMetaAilmentsRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");

    /**
     * Create a {@code move_meta_ailments} table reference
     */
    public MoveMetaAilments() {
        this("move_meta_ailments", null);
    }

    private MoveMetaAilments(String alias, Table<MoveMetaAilmentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private MoveMetaAilments(String alias, Table<MoveMetaAilmentsRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code move_meta_ailments} table reference
     */
    public MoveMetaAilments(String alias) {
        this(alias, MOVE_META_AILMENTS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MoveMetaAilmentsRecord> getPrimaryKey() {
        return Keys.PK_MOVE_META_AILMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MoveMetaAilmentsRecord>> getKeys() {
        return Arrays.<UniqueKey<MoveMetaAilmentsRecord>>asList(Keys.PK_MOVE_META_AILMENTS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaAilments as(String alias) {
        return new MoveMetaAilments(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MoveMetaAilmentsRecord> getRecordType() {
        return MoveMetaAilmentsRecord.class;
    }

    /**
     * Rename this table
     */
    public MoveMetaAilments rename(String name) {
        return new MoveMetaAilments(name, null);
    }
}
