/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.MoveTargetProseRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MoveTargetProse extends TableImpl<MoveTargetProseRecord> {

    /**
     * The reference instance of {@code move_target_prose}
     */
    public static final MoveTargetProse MOVE_TARGET_PROSE = new MoveTargetProse();
    private static final long serialVersionUID = 1917668398;
    /**
     * The column {@code move_target_prose.move_target_id}.
     */
    public final TableField<MoveTargetProseRecord, Integer> MOVE_TARGET_ID =
            createField("move_target_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_target_prose.local_language_id}.
     */
    public final TableField<MoveTargetProseRecord, Integer> LOCAL_LANGUAGE_ID =
            createField("local_language_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_target_prose.name}.
     */
    public final TableField<MoveTargetProseRecord, String> NAME =
            createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(79), this, "");
    /**
     * The column {@code move_target_prose.description}.
     */
    public final TableField<MoveTargetProseRecord, String> DESCRIPTION =
            createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a {@code move_target_prose} table reference
     */
    public MoveTargetProse() {
        this("move_target_prose", null);
    }

    private MoveTargetProse(String alias, Table<MoveTargetProseRecord> aliased) {
        this(alias, aliased, null);
    }

    private MoveTargetProse(String alias, Table<MoveTargetProseRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code move_target_prose} table reference
     */
    public MoveTargetProse(String alias) {
        this(alias, MOVE_TARGET_PROSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MoveTargetProseRecord> getPrimaryKey() {
        return Keys.PK_MOVE_TARGET_PROSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MoveTargetProseRecord>> getKeys() {
        return Arrays.<UniqueKey<MoveTargetProseRecord>>asList(Keys.PK_MOVE_TARGET_PROSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MoveTargetProseRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MoveTargetProseRecord, ?>>asList(Keys.FK_MOVE_TARGET_PROSE_MOVE_TARGETS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveTargetProse as(String alias) {
        return new MoveTargetProse(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MoveTargetProseRecord> getRecordType() {
        return MoveTargetProseRecord.class;
    }

    /**
     * Rename this table
     */
    public MoveTargetProse rename(String name) {
        return new MoveTargetProse(name, null);
    }
}
