/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.MoveDamageClassesRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MoveDamageClasses extends TableImpl<MoveDamageClassesRecord> {

    /**
     * The reference instance of {@code move_damage_classes}
     */
    public static final MoveDamageClasses MOVE_DAMAGE_CLASSES = new MoveDamageClasses();
    private static final long serialVersionUID = 131263802;
    /**
     * The column {@code move_damage_classes.id}.
     */
    public final TableField<MoveDamageClassesRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_damage_classes.identifier}.
     */
    public final TableField<MoveDamageClassesRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");

    /**
     * Create a {@code move_damage_classes} table reference
     */
    public MoveDamageClasses() {
        this("move_damage_classes", null);
    }

    private MoveDamageClasses(String alias, Table<MoveDamageClassesRecord> aliased) {
        this(alias, aliased, null);
    }

    private MoveDamageClasses(String alias, Table<MoveDamageClassesRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code move_damage_classes} table reference
     */
    public MoveDamageClasses(String alias) {
        this(alias, MOVE_DAMAGE_CLASSES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MoveDamageClassesRecord> getPrimaryKey() {
        return Keys.PK_MOVE_DAMAGE_CLASSES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MoveDamageClassesRecord>> getKeys() {
        return Arrays.<UniqueKey<MoveDamageClassesRecord>>asList(Keys.PK_MOVE_DAMAGE_CLASSES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveDamageClasses as(String alias) {
        return new MoveDamageClasses(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MoveDamageClassesRecord> getRecordType() {
        return MoveDamageClassesRecord.class;
    }

    /**
     * Rename this table
     */
    public MoveDamageClasses rename(String name) {
        return new MoveDamageClasses(name, null);
    }
}
