/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.MoveBattleStylesRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MoveBattleStyles extends TableImpl<MoveBattleStylesRecord> {

    /**
     * The reference instance of {@code move_battle_styles}
     */
    public static final MoveBattleStyles MOVE_BATTLE_STYLES = new MoveBattleStyles();
    private static final long serialVersionUID = -726060318;
    /**
     * The column {@code move_battle_styles.id}.
     */
    public final TableField<MoveBattleStylesRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_battle_styles.identifier}.
     */
    public final TableField<MoveBattleStylesRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");

    /**
     * Create a {@code move_battle_styles} table reference
     */
    public MoveBattleStyles() {
        this("move_battle_styles", null);
    }

    private MoveBattleStyles(String alias, Table<MoveBattleStylesRecord> aliased) {
        this(alias, aliased, null);
    }

    private MoveBattleStyles(String alias, Table<MoveBattleStylesRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code move_battle_styles} table reference
     */
    public MoveBattleStyles(String alias) {
        this(alias, MOVE_BATTLE_STYLES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MoveBattleStylesRecord> getPrimaryKey() {
        return Keys.PK_MOVE_BATTLE_STYLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MoveBattleStylesRecord>> getKeys() {
        return Arrays.<UniqueKey<MoveBattleStylesRecord>>asList(Keys.PK_MOVE_BATTLE_STYLES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveBattleStyles as(String alias) {
        return new MoveBattleStyles(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MoveBattleStylesRecord> getRecordType() {
        return MoveBattleStylesRecord.class;
    }

    /**
     * Rename this table
     */
    public MoveBattleStyles rename(String name) {
        return new MoveBattleStyles(name, null);
    }
}
