/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.MoveMetaStatChangesRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MoveMetaStatChanges extends TableImpl<MoveMetaStatChangesRecord> {

    /**
     * The reference instance of {@code move_meta_stat_changes}
     */
    public static final MoveMetaStatChanges MOVE_META_STAT_CHANGES = new MoveMetaStatChanges();
    private static final long serialVersionUID = -588175426;
    /**
     * The column {@code move_meta_stat_changes.move_id}.
     */
    public final TableField<MoveMetaStatChangesRecord, Integer> MOVE_ID =
            createField("move_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_meta_stat_changes.stat_id}.
     */
    public final TableField<MoveMetaStatChangesRecord, Integer> STAT_ID =
            createField("stat_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_meta_stat_changes.change}.
     */
    public final TableField<MoveMetaStatChangesRecord, Integer> CHANGE =
            createField("change", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a {@code move_meta_stat_changes} table reference
     */
    public MoveMetaStatChanges() {
        this("move_meta_stat_changes", null);
    }

    private MoveMetaStatChanges(String alias, Table<MoveMetaStatChangesRecord> aliased) {
        this(alias, aliased, null);
    }

    private MoveMetaStatChanges(String alias, Table<MoveMetaStatChangesRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code move_meta_stat_changes} table reference
     */
    public MoveMetaStatChanges(String alias) {
        this(alias, MOVE_META_STAT_CHANGES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MoveMetaStatChangesRecord> getPrimaryKey() {
        return Keys.PK_MOVE_META_STAT_CHANGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MoveMetaStatChangesRecord>> getKeys() {
        return Arrays.<UniqueKey<MoveMetaStatChangesRecord>>asList(Keys.PK_MOVE_META_STAT_CHANGES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MoveMetaStatChangesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MoveMetaStatChangesRecord, ?>>asList(Keys.FK_MOVE_META_STAT_CHANGES_MOVES_1,
                                                                       Keys.FK_MOVE_META_STAT_CHANGES_STATS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaStatChanges as(String alias) {
        return new MoveMetaStatChanges(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MoveMetaStatChangesRecord> getRecordType() {
        return MoveMetaStatChangesRecord.class;
    }

    /**
     * Rename this table
     */
    public MoveMetaStatChanges rename(String name) {
        return new MoveMetaStatChanges(name, null);
    }
}
