/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.MoveFlagMapRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MoveFlagMap extends TableImpl<MoveFlagMapRecord> {

    /**
     * The reference instance of {@code move_flag_map}
     */
    public static final MoveFlagMap MOVE_FLAG_MAP = new MoveFlagMap();
    private static final long serialVersionUID = -1925657896;
    /**
     * The column {@code move_flag_map.move_id}.
     */
    public final TableField<MoveFlagMapRecord, Integer> MOVE_ID =
            createField("move_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_flag_map.move_flag_id}.
     */
    public final TableField<MoveFlagMapRecord, Integer> MOVE_FLAG_ID =
            createField("move_flag_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a {@code move_flag_map} table reference
     */
    public MoveFlagMap() {
        this("move_flag_map", null);
    }

    private MoveFlagMap(String alias, Table<MoveFlagMapRecord> aliased) {
        this(alias, aliased, null);
    }

    private MoveFlagMap(String alias, Table<MoveFlagMapRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code move_flag_map} table reference
     */
    public MoveFlagMap(String alias) {
        this(alias, MOVE_FLAG_MAP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MoveFlagMapRecord> getPrimaryKey() {
        return Keys.PK_MOVE_FLAG_MAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MoveFlagMapRecord>> getKeys() {
        return Arrays.<UniqueKey<MoveFlagMapRecord>>asList(Keys.PK_MOVE_FLAG_MAP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MoveFlagMapRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MoveFlagMapRecord, ?>>asList(Keys.FK_MOVE_FLAG_MAP_MOVES_1,
                                                               Keys.FK_MOVE_FLAG_MAP_MOVE_FLAGS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveFlagMap as(String alias) {
        return new MoveFlagMap(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MoveFlagMapRecord> getRecordType() {
        return MoveFlagMapRecord.class;
    }

    /**
     * Rename this table
     */
    public MoveFlagMap rename(String name) {
        return new MoveFlagMap(name, null);
    }
}
