/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.MoveFlagProseRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MoveFlagProse extends TableImpl<MoveFlagProseRecord> {

    /**
     * The reference instance of {@code move_flag_prose}
     */
    public static final MoveFlagProse MOVE_FLAG_PROSE = new MoveFlagProse();
    private static final long serialVersionUID = -2105128279;
    /**
     * The column {@code move_flag_prose.move_flag_id}.
     */
    public final TableField<MoveFlagProseRecord, Integer> MOVE_FLAG_ID =
            createField("move_flag_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_flag_prose.local_language_id}.
     */
    public final TableField<MoveFlagProseRecord, Integer> LOCAL_LANGUAGE_ID =
            createField("local_language_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code move_flag_prose.name}.
     */
    public final TableField<MoveFlagProseRecord, String> NAME =
            createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(79), this, "");
    /**
     * The column {@code move_flag_prose.description}.
     */
    public final TableField<MoveFlagProseRecord, String> DESCRIPTION =
            createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a {@code move_flag_prose} table reference
     */
    public MoveFlagProse() {
        this("move_flag_prose", null);
    }

    private MoveFlagProse(String alias, Table<MoveFlagProseRecord> aliased) {
        this(alias, aliased, null);
    }

    private MoveFlagProse(String alias, Table<MoveFlagProseRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code move_flag_prose} table reference
     */
    public MoveFlagProse(String alias) {
        this(alias, MOVE_FLAG_PROSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MoveFlagProseRecord> getPrimaryKey() {
        return Keys.PK_MOVE_FLAG_PROSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MoveFlagProseRecord>> getKeys() {
        return Arrays.<UniqueKey<MoveFlagProseRecord>>asList(Keys.PK_MOVE_FLAG_PROSE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MoveFlagProseRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MoveFlagProseRecord, ?>>asList(Keys.FK_MOVE_FLAG_PROSE_MOVE_FLAGS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveFlagProse as(String alias) {
        return new MoveFlagProse(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MoveFlagProseRecord> getRecordType() {
        return MoveFlagProseRecord.class;
    }

    /**
     * Rename this table
     */
    public MoveFlagProse rename(String name) {
        return new MoveFlagProse(name, null);
    }
}
