/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.NaturesRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class Natures extends TableImpl<NaturesRecord> {

    /**
     * The reference instance of {@code natures}
     */
    public static final Natures NATURES = new Natures();
    private static final long serialVersionUID = 1320858671;
    /**
     * The column {@code natures.id}.
     */
    public final TableField<NaturesRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code natures.identifier}.
     */
    public final TableField<NaturesRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");
    /**
     * The column {@code natures.decreased_stat_id}.
     */
    public final TableField<NaturesRecord, Integer> DECREASED_STAT_ID =
            createField("decreased_stat_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code natures.increased_stat_id}.
     */
    public final TableField<NaturesRecord, Integer> INCREASED_STAT_ID =
            createField("increased_stat_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code natures.hates_flavor_id}.
     */
    public final TableField<NaturesRecord, Integer> HATES_FLAVOR_ID =
            createField("hates_flavor_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code natures.likes_flavor_id}.
     */
    public final TableField<NaturesRecord, Integer> LIKES_FLAVOR_ID =
            createField("likes_flavor_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code natures.game_index}.
     */
    public final TableField<NaturesRecord, Integer> GAME_INDEX =
            createField("game_index", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a {@code natures} table reference
     */
    public Natures() {
        this("natures", null);
    }

    private Natures(String alias, Table<NaturesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Natures(String alias, Table<NaturesRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code natures} table reference
     */
    public Natures(String alias) {
        this(alias, NATURES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<NaturesRecord> getPrimaryKey() {
        return Keys.PK_NATURES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<NaturesRecord>> getKeys() {
        return Arrays.<UniqueKey<NaturesRecord>>asList(Keys.PK_NATURES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<NaturesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<NaturesRecord, ?>>asList(Keys.FK_NATURES_STATS_2, Keys.FK_NATURES_STATS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Natures as(String alias) {
        return new Natures(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NaturesRecord> getRecordType() {
        return NaturesRecord.class;
    }

    /**
     * Rename this table
     */
    public Natures rename(String name) {
        return new Natures(name, null);
    }
}
