/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.PokemonFormsRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class PokemonForms extends TableImpl<PokemonFormsRecord> {

    /**
     * The reference instance of {@code pokemon_forms}
     */
    public static final PokemonForms POKEMON_FORMS = new PokemonForms();
    private static final long serialVersionUID = -933615933;
    /**
     * The column {@code pokemon_forms.id}.
     */
    public final TableField<PokemonFormsRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_forms.identifier}.
     */
    public final TableField<PokemonFormsRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");
    /**
     * The column {@code pokemon_forms.form_identifier}.
     */
    public final TableField<PokemonFormsRecord, String> FORM_IDENTIFIER =
            createField("form_identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79), this, "");
    /**
     * The column {@code pokemon_forms.pokemon_id}.
     */
    public final TableField<PokemonFormsRecord, Integer> POKEMON_ID =
            createField("pokemon_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_forms.introduced_in_version_group_id}.
     */
    public final TableField<PokemonFormsRecord, Integer> INTRODUCED_IN_VERSION_GROUP_ID =
            createField("introduced_in_version_group_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_forms.is_default}.
     */
    public final TableField<PokemonFormsRecord, Boolean> IS_DEFAULT =
            createField("is_default", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");
    /**
     * The column {@code pokemon_forms.is_battle_only}.
     */
    public final TableField<PokemonFormsRecord, Boolean> IS_BATTLE_ONLY =
            createField("is_battle_only", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");
    /**
     * The column {@code pokemon_forms.is_mega}.
     */
    public final TableField<PokemonFormsRecord, Boolean> IS_MEGA =
            createField("is_mega", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");
    /**
     * The column {@code pokemon_forms.form_order}.
     */
    public final TableField<PokemonFormsRecord, Integer> FORM_ORDER =
            createField("form_order", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_forms.order}.
     */
    public final TableField<PokemonFormsRecord, Integer> ORDER =
            createField("order", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a {@code pokemon_forms} table reference
     */
    public PokemonForms() {
        this("pokemon_forms", null);
    }

    private PokemonForms(String alias, Table<PokemonFormsRecord> aliased) {
        this(alias, aliased, null);
    }

    private PokemonForms(String alias, Table<PokemonFormsRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code pokemon_forms} table reference
     */
    public PokemonForms(String alias) {
        this(alias, POKEMON_FORMS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PokemonFormsRecord> getPrimaryKey() {
        return Keys.PK_POKEMON_FORMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PokemonFormsRecord>> getKeys() {
        return Arrays.<UniqueKey<PokemonFormsRecord>>asList(Keys.PK_POKEMON_FORMS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PokemonFormsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PokemonFormsRecord, ?>>asList(Keys.FK_POKEMON_FORMS_POKEMON_1,
                                                                Keys.FK_POKEMON_FORMS_VERSION_GROUPS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonForms as(String alias) {
        return new PokemonForms(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PokemonFormsRecord> getRecordType() {
        return PokemonFormsRecord.class;
    }

    /**
     * Rename this table
     */
    public PokemonForms rename(String name) {
        return new PokemonForms(name, null);
    }
}
