/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.PokedexVersionGroupsRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class PokedexVersionGroups extends TableImpl<PokedexVersionGroupsRecord> {

    /**
     * The reference instance of {@code pokedex_version_groups}
     */
    public static final PokedexVersionGroups POKEDEX_VERSION_GROUPS = new PokedexVersionGroups();
    private static final long serialVersionUID = 1668901445;
    /**
     * The column {@code pokedex_version_groups.pokedex_id}.
     */
    public final TableField<PokedexVersionGroupsRecord, Integer> POKEDEX_ID =
            createField("pokedex_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokedex_version_groups.version_group_id}.
     */
    public final TableField<PokedexVersionGroupsRecord, Integer> VERSION_GROUP_ID =
            createField("version_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a {@code pokedex_version_groups} table reference
     */
    public PokedexVersionGroups() {
        this("pokedex_version_groups", null);
    }

    private PokedexVersionGroups(String alias, Table<PokedexVersionGroupsRecord> aliased) {
        this(alias, aliased, null);
    }

    private PokedexVersionGroups(String alias, Table<PokedexVersionGroupsRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code pokedex_version_groups} table reference
     */
    public PokedexVersionGroups(String alias) {
        this(alias, POKEDEX_VERSION_GROUPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PokedexVersionGroupsRecord> getPrimaryKey() {
        return Keys.PK_POKEDEX_VERSION_GROUPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PokedexVersionGroupsRecord>> getKeys() {
        return Arrays.<UniqueKey<PokedexVersionGroupsRecord>>asList(Keys.PK_POKEDEX_VERSION_GROUPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PokedexVersionGroupsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PokedexVersionGroupsRecord, ?>>asList(Keys.FK_POKEDEX_VERSION_GROUPS_POKEDEXES_1,
                                                                        Keys.FK_POKEDEX_VERSION_GROUPS_VERSION_GROUPS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokedexVersionGroups as(String alias) {
        return new PokedexVersionGroups(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PokedexVersionGroupsRecord> getRecordType() {
        return PokedexVersionGroupsRecord.class;
    }

    /**
     * Rename this table
     */
    public PokedexVersionGroups rename(String name) {
        return new PokedexVersionGroups(name, null);
    }
}
