/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.PokemonTypesRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class PokemonTypes extends TableImpl<PokemonTypesRecord> {

    /**
     * The reference instance of {@code pokemon_types}
     */
    public static final PokemonTypes POKEMON_TYPES = new PokemonTypes();
    private static final long serialVersionUID = -1192243095;
    /**
     * The column {@code pokemon_types.pokemon_id}.
     */
    public final TableField<PokemonTypesRecord, Integer> POKEMON_ID =
            createField("pokemon_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_types.type_id}.
     */
    public final TableField<PokemonTypesRecord, Integer> TYPE_ID =
            createField("type_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_types.slot}.
     */
    public final TableField<PokemonTypesRecord, Integer> SLOT =
            createField("slot", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a {@code pokemon_types} table reference
     */
    public PokemonTypes() {
        this("pokemon_types", null);
    }

    private PokemonTypes(String alias, Table<PokemonTypesRecord> aliased) {
        this(alias, aliased, null);
    }

    private PokemonTypes(String alias, Table<PokemonTypesRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code pokemon_types} table reference
     */
    public PokemonTypes(String alias) {
        this(alias, POKEMON_TYPES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PokemonTypesRecord> getPrimaryKey() {
        return Keys.PK_POKEMON_TYPES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PokemonTypesRecord>> getKeys() {
        return Arrays.<UniqueKey<PokemonTypesRecord>>asList(Keys.PK_POKEMON_TYPES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PokemonTypesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PokemonTypesRecord, ?>>asList(Keys.FK_POKEMON_TYPES_POKEMON_1,
                                                                Keys.FK_POKEMON_TYPES_TYPES_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonTypes as(String alias) {
        return new PokemonTypes(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PokemonTypesRecord> getRecordType() {
        return PokemonTypesRecord.class;
    }

    /**
     * Rename this table
     */
    public PokemonTypes rename(String name) {
        return new PokemonTypes(name, null);
    }
}
