/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.PokemonEvolutionRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class PokemonEvolution extends TableImpl<PokemonEvolutionRecord> {

    /**
     * The reference instance of {@code pokemon_evolution}
     */
    public static final PokemonEvolution POKEMON_EVOLUTION = new PokemonEvolution();
    private static final long serialVersionUID = -621549647;
    /**
     * The column {@code pokemon_evolution.id}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_evolution.evolved_species_id}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> EVOLVED_SPECIES_ID =
            createField("evolved_species_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_evolution.evolution_trigger_id}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> EVOLUTION_TRIGGER_ID =
            createField("evolution_trigger_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_evolution.trigger_item_id}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> TRIGGER_ITEM_ID =
            createField("trigger_item_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.minimum_level}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> MINIMUM_LEVEL =
            createField("minimum_level", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.gender_id}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> GENDER_ID =
            createField("gender_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.location_id}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> LOCATION_ID =
            createField("location_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.held_item_id}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> HELD_ITEM_ID =
            createField("held_item_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.time_of_day}.
     */
    public final TableField<PokemonEvolutionRecord, String> TIME_OF_DAY =
            createField("time_of_day", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");
    /**
     * The column {@code pokemon_evolution.known_move_id}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> KNOWN_MOVE_ID =
            createField("known_move_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.known_move_type_id}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> KNOWN_MOVE_TYPE_ID =
            createField("known_move_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.minimum_happiness}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> MINIMUM_HAPPINESS =
            createField("minimum_happiness", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.minimum_beauty}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> MINIMUM_BEAUTY =
            createField("minimum_beauty", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.minimum_affection}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> MINIMUM_AFFECTION =
            createField("minimum_affection", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.relative_physical_stats}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> RELATIVE_PHYSICAL_STATS =
            createField("relative_physical_stats", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.party_species_id}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> PARTY_SPECIES_ID =
            createField("party_species_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.party_type_id}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> PARTY_TYPE_ID =
            createField("party_type_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.trade_species_id}.
     */
    public final TableField<PokemonEvolutionRecord, Integer> TRADE_SPECIES_ID =
            createField("trade_species_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_evolution.needs_overworld_rain}.
     */
    public final TableField<PokemonEvolutionRecord, Boolean> NEEDS_OVERWORLD_RAIN =
            createField("needs_overworld_rain", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");
    /**
     * The column {@code pokemon_evolution.turn_upside_down}.
     */
    public final TableField<PokemonEvolutionRecord, Boolean> TURN_UPSIDE_DOWN =
            createField("turn_upside_down", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * Create a {@code pokemon_evolution} table reference
     */
    public PokemonEvolution() {
        this("pokemon_evolution", null);
    }

    private PokemonEvolution(String alias, Table<PokemonEvolutionRecord> aliased) {
        this(alias, aliased, null);
    }

    private PokemonEvolution(String alias, Table<PokemonEvolutionRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code pokemon_evolution} table reference
     */
    public PokemonEvolution(String alias) {
        this(alias, POKEMON_EVOLUTION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PokemonEvolutionRecord> getPrimaryKey() {
        return Keys.PK_POKEMON_EVOLUTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PokemonEvolutionRecord>> getKeys() {
        return Arrays.<UniqueKey<PokemonEvolutionRecord>>asList(Keys.PK_POKEMON_EVOLUTION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PokemonEvolutionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PokemonEvolutionRecord, ?>>asList(Keys.FK_POKEMON_EVOLUTION_POKEMON_SPECIES_3,
                                                                    Keys.FK_POKEMON_EVOLUTION_EVOLUTION_TRIGGERS_1,
                                                                    Keys.FK_POKEMON_EVOLUTION_ITEMS_2,
                                                                    Keys.FK_POKEMON_EVOLUTION_GENDERS_1,
                                                                    Keys.FK_POKEMON_EVOLUTION_ITEMS_1,
                                                                    Keys.FK_POKEMON_EVOLUTION_MOVES_1,
                                                                    Keys.FK_POKEMON_EVOLUTION_TYPES_2,
                                                                    Keys.FK_POKEMON_EVOLUTION_POKEMON_SPECIES_2,
                                                                    Keys.FK_POKEMON_EVOLUTION_TYPES_1,
                                                                    Keys.FK_POKEMON_EVOLUTION_POKEMON_SPECIES_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonEvolution as(String alias) {
        return new PokemonEvolution(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PokemonEvolutionRecord> getRecordType() {
        return PokemonEvolutionRecord.class;
    }

    /**
     * Rename this table
     */
    public PokemonEvolution rename(String name) {
        return new PokemonEvolution(name, null);
    }
}
