/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.PokemonSpeciesRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class PokemonSpecies extends TableImpl<PokemonSpeciesRecord> {

    /**
     * The reference instance of {@code pokemon_species}
     */
    public static final PokemonSpecies POKEMON_SPECIES = new PokemonSpecies();
    private static final long serialVersionUID = 368668984;
    /**
     * The column {@code pokemon_species.id}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_species.identifier}.
     */
    public final TableField<PokemonSpeciesRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");
    /**
     * The column {@code pokemon_species.generation_id}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> GENERATION_ID =
            createField("generation_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_species.evolves_from_species_id}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> EVOLVES_FROM_SPECIES_ID =
            createField("evolves_from_species_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_species.evolution_chain_id}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> EVOLUTION_CHAIN_ID =
            createField("evolution_chain_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_species.color_id}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> COLOR_ID =
            createField("color_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_species.shape_id}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> SHAPE_ID =
            createField("shape_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_species.habitat_id}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> HABITAT_ID =
            createField("habitat_id", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code pokemon_species.gender_rate}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> GENDER_RATE =
            createField("gender_rate", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_species.capture_rate}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> CAPTURE_RATE =
            createField("capture_rate", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_species.base_happiness}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> BASE_HAPPINESS =
            createField("base_happiness", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_species.is_baby}.
     */
    public final TableField<PokemonSpeciesRecord, Boolean> IS_BABY =
            createField("is_baby", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");
    /**
     * The column {@code pokemon_species.hatch_counter}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> HATCH_COUNTER =
            createField("hatch_counter", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_species.has_gender_differences}.
     */
    public final TableField<PokemonSpeciesRecord, Boolean> HAS_GENDER_DIFFERENCES =
            createField("has_gender_differences", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");
    /**
     * The column {@code pokemon_species.growth_rate_id}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> GROWTH_RATE_ID =
            createField("growth_rate_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_species.forms_switchable}.
     */
    public final TableField<PokemonSpeciesRecord, Boolean> FORMS_SWITCHABLE =
            createField("forms_switchable", org.jooq.impl.SQLDataType.BOOLEAN.nullable(false), this, "");
    /**
     * The column {@code pokemon_species.order}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> ORDER =
            createField("order", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code pokemon_species.conquest_order}.
     */
    public final TableField<PokemonSpeciesRecord, Integer> CONQUEST_ORDER =
            createField("conquest_order", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a {@code pokemon_species} table reference
     */
    public PokemonSpecies() {
        this("pokemon_species", null);
    }

    private PokemonSpecies(String alias, Table<PokemonSpeciesRecord> aliased) {
        this(alias, aliased, null);
    }

    private PokemonSpecies(String alias, Table<PokemonSpeciesRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code pokemon_species} table reference
     */
    public PokemonSpecies(String alias) {
        this(alias, POKEMON_SPECIES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PokemonSpeciesRecord> getPrimaryKey() {
        return Keys.PK_POKEMON_SPECIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PokemonSpeciesRecord>> getKeys() {
        return Arrays.<UniqueKey<PokemonSpeciesRecord>>asList(Keys.PK_POKEMON_SPECIES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PokemonSpeciesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PokemonSpeciesRecord, ?>>asList(Keys.FK_POKEMON_SPECIES_GENERATIONS_1,
                                                                  Keys.FK_POKEMON_SPECIES_POKEMON_SPECIES_1,
                                                                  Keys.FK_POKEMON_SPECIES_EVOLUTION_CHAINS_1,
                                                                  Keys.FK_POKEMON_SPECIES_GROWTH_RATES_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpecies as(String alias) {
        return new PokemonSpecies(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PokemonSpeciesRecord> getRecordType() {
        return PokemonSpeciesRecord.class;
    }

    /**
     * Rename this table
     */
    public PokemonSpecies rename(String name) {
        return new PokemonSpecies(name, null);
    }
}
