/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.StatHintNamesRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class StatHintNames extends TableImpl<StatHintNamesRecord> {

    /**
     * The reference instance of {@code stat_hint_names}
     */
    public static final StatHintNames STAT_HINT_NAMES = new StatHintNames();
    private static final long serialVersionUID = 1788655416;
    /**
     * The column {@code stat_hint_names.stat_hint_id}.
     */
    public final TableField<StatHintNamesRecord, Integer> STAT_HINT_ID =
            createField("stat_hint_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code stat_hint_names.local_language_id}.
     */
    public final TableField<StatHintNamesRecord, Integer> LOCAL_LANGUAGE_ID =
            createField("local_language_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code stat_hint_names.message}.
     */
    public final TableField<StatHintNamesRecord, String> MESSAGE =
            createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");

    /**
     * Create a {@code stat_hint_names} table reference
     */
    public StatHintNames() {
        this("stat_hint_names", null);
    }

    private StatHintNames(String alias, Table<StatHintNamesRecord> aliased) {
        this(alias, aliased, null);
    }

    private StatHintNames(String alias, Table<StatHintNamesRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code stat_hint_names} table reference
     */
    public StatHintNames(String alias) {
        this(alias, STAT_HINT_NAMES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StatHintNamesRecord> getPrimaryKey() {
        return Keys.PK_STAT_HINT_NAMES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StatHintNamesRecord>> getKeys() {
        return Arrays.<UniqueKey<StatHintNamesRecord>>asList(Keys.PK_STAT_HINT_NAMES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StatHintNamesRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StatHintNamesRecord, ?>>asList(Keys.FK_STAT_HINT_NAMES_STAT_HINTS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatHintNames as(String alias) {
        return new StatHintNames(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StatHintNamesRecord> getRecordType() {
        return StatHintNamesRecord.class;
    }

    /**
     * Rename this table
     */
    public StatHintNames rename(String name) {
        return new StatHintNames(name, null);
    }
}
