/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.VersionsRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class Versions extends TableImpl<VersionsRecord> {

    /**
     * The reference instance of {@code versions}
     */
    public static final Versions VERSIONS = new Versions();
    private static final long serialVersionUID = 2006012527;
    /**
     * The column {@code versions.id}.
     */
    public final TableField<VersionsRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code versions.version_group_id}.
     */
    public final TableField<VersionsRecord, Integer> VERSION_GROUP_ID =
            createField("version_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code versions.identifier}.
     */
    public final TableField<VersionsRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");

    /**
     * Create a {@code versions} table reference
     */
    public Versions() {
        this("versions", null);
    }

    private Versions(String alias, Table<VersionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Versions(String alias, Table<VersionsRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code versions} table reference
     */
    public Versions(String alias) {
        this(alias, VERSIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VersionsRecord> getPrimaryKey() {
        return Keys.PK_VERSIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VersionsRecord>> getKeys() {
        return Arrays.<UniqueKey<VersionsRecord>>asList(Keys.PK_VERSIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<VersionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VersionsRecord, ?>>asList(Keys.FK_VERSIONS_VERSION_GROUPS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Versions as(String alias) {
        return new Versions(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VersionsRecord> getRecordType() {
        return VersionsRecord.class;
    }

    /**
     * Rename this table
     */
    public Versions rename(String name) {
        return new Versions(name, null);
    }
}
