/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.VersionGroupRegionsRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class VersionGroupRegions extends TableImpl<VersionGroupRegionsRecord> {

    /**
     * The reference instance of {@code version_group_regions}
     */
    public static final VersionGroupRegions VERSION_GROUP_REGIONS = new VersionGroupRegions();
    private static final long serialVersionUID = -1500277714;
    /**
     * The column {@code version_group_regions.version_group_id}.
     */
    public final TableField<VersionGroupRegionsRecord, Integer> VERSION_GROUP_ID =
            createField("version_group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code version_group_regions.region_id}.
     */
    public final TableField<VersionGroupRegionsRecord, Integer> REGION_ID =
            createField("region_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a {@code version_group_regions} table reference
     */
    public VersionGroupRegions() {
        this("version_group_regions", null);
    }

    private VersionGroupRegions(String alias, Table<VersionGroupRegionsRecord> aliased) {
        this(alias, aliased, null);
    }

    private VersionGroupRegions(String alias, Table<VersionGroupRegionsRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code version_group_regions} table reference
     */
    public VersionGroupRegions(String alias) {
        this(alias, VERSION_GROUP_REGIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VersionGroupRegionsRecord> getPrimaryKey() {
        return Keys.PK_VERSION_GROUP_REGIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VersionGroupRegionsRecord>> getKeys() {
        return Arrays.<UniqueKey<VersionGroupRegionsRecord>>asList(Keys.PK_VERSION_GROUP_REGIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<VersionGroupRegionsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VersionGroupRegionsRecord, ?>>asList(Keys.FK_VERSION_GROUP_REGIONS_VERSION_GROUPS_1,
                                                                       Keys.FK_VERSION_GROUP_REGIONS_REGIONS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionGroupRegions as(String alias) {
        return new VersionGroupRegions(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VersionGroupRegionsRecord> getRecordType() {
        return VersionGroupRegionsRecord.class;
    }

    /**
     * Rename this table
     */
    public VersionGroupRegions rename(String name) {
        return new VersionGroupRegions(name, null);
    }
}
