/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables;

import com.com.ivbot.sql.schema.DefaultSchema;
import com.com.ivbot.sql.schema.Keys;
import com.com.ivbot.sql.schema.tables.records.VersionGroupsRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class VersionGroups extends TableImpl<VersionGroupsRecord> {

    /**
     * The reference instance of {@code version_groups}
     */
    public static final VersionGroups VERSION_GROUPS = new VersionGroups();
    private static final long serialVersionUID = -1166366179;
    /**
     * The column {@code version_groups.id}.
     */
    public final TableField<VersionGroupsRecord, Integer> ID =
            createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code version_groups.identifier}.
     */
    public final TableField<VersionGroupsRecord, String> IDENTIFIER =
            createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(79).nullable(false), this, "");
    /**
     * The column {@code version_groups.generation_id}.
     */
    public final TableField<VersionGroupsRecord, Integer> GENERATION_ID =
            createField("generation_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");
    /**
     * The column {@code version_groups.order}.
     */
    public final TableField<VersionGroupsRecord, Integer> ORDER =
            createField("order", org.jooq.impl.SQLDataType.INTEGER, this, "");
    /**
     * The column {@code version_groups.preference_order}.
     */
    public final TableField<VersionGroupsRecord, Integer> PREFERENCE_ORDER =
            createField("preference_order", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a {@code version_groups} table reference
     */
    public VersionGroups() {
        this("version_groups", null);
    }

    private VersionGroups(String alias, Table<VersionGroupsRecord> aliased) {
        this(alias, aliased, null);
    }

    private VersionGroups(String alias, Table<VersionGroupsRecord> aliased, Field<?>[] parameters) {
        super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
    }

    /**
     * Create an aliased {@code version_groups} table reference
     */
    public VersionGroups(String alias) {
        this(alias, VERSION_GROUPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VersionGroupsRecord> getPrimaryKey() {
        return Keys.PK_VERSION_GROUPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VersionGroupsRecord>> getKeys() {
        return Arrays.<UniqueKey<VersionGroupsRecord>>asList(Keys.PK_VERSION_GROUPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<VersionGroupsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VersionGroupsRecord, ?>>asList(Keys.FK_VERSION_GROUPS_GENERATIONS_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VersionGroups as(String alias) {
        return new VersionGroups(alias, this);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VersionGroupsRecord> getRecordType() {
        return VersionGroupsRecord.class;
    }

    /**
     * Rename this table
     */
    public VersionGroups rename(String name) {
        return new VersionGroups(name, null);
    }
}
