/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.Abilities;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class AbilitiesRecord extends UpdatableRecordImpl<AbilitiesRecord>
        implements Record4<Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 426414346;

    /**
     * Create a detached AbilitiesRecord
     */
    public AbilitiesRecord() {
        super(Abilities.ABILITIES);
    }

    /**
     * Create a detached, initialised AbilitiesRecord
     */
    public AbilitiesRecord(Integer id, String identifier, Integer generationId, Integer isMainSeries) {
        super(Abilities.ABILITIES);

        setValue(0, id);
        setValue(1, identifier);
        setValue(2, generationId);
        setValue(3, isMainSeries);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Abilities.ABILITIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Abilities.ABILITIES.IDENTIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Abilities.ABILITIES.GENERATION_ID;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Abilities.ABILITIES.IS_MAIN_SERIES;
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * Getter for {@code abilities.id}.
     */
    public Integer getId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code abilities.id}.
     */
    public void setId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIdentifier();
    }

    /**
     * Getter for {@code abilities.identifier}.
     */
    public String getIdentifier() {
        return (String) getValue(1);
    }

    /**
     * Setter for {@code abilities.identifier}.
     */
    public void setIdentifier(String value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGenerationId();
    }

    /**
     * Getter for {@code abilities.generation_id}.
     */
    public Integer getGenerationId() {
        return (Integer) getValue(2);
    }

    /**
     * Setter for {@code abilities.generation_id}.
     */
    public void setGenerationId(Integer value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIsMainSeries();
    }

    /**
     * Getter for {@code abilities.is_main_series}.
     */
    public Integer getIsMainSeries() {
        return (Integer) getValue(3);
    }

    /**
     * Setter for {@code abilities.is_main_series}.
     */
    public void setIsMainSeries(Integer value) {
        setValue(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AbilitiesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AbilitiesRecord value2(String value) {
        setIdentifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AbilitiesRecord value3(Integer value) {
        setGenerationId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public AbilitiesRecord value4(Integer value) {
        setIsMainSeries(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AbilitiesRecord values(Integer value1, String value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
