/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.EvolutionChains;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class EvolutionChainsRecord extends UpdatableRecordImpl<EvolutionChainsRecord>
        implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -537943530;

    /**
     * Create a detached EvolutionChainsRecord
     */
    public EvolutionChainsRecord() {
        super(EvolutionChains.EVOLUTION_CHAINS);
    }

    /**
     * Create a detached, initialised EvolutionChainsRecord
     */
    public EvolutionChainsRecord(Integer id, Integer babyTriggerItemId) {
        super(EvolutionChains.EVOLUTION_CHAINS);

        setValue(0, id);
        setValue(1, babyTriggerItemId);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return EvolutionChains.EVOLUTION_CHAINS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return EvolutionChains.EVOLUTION_CHAINS.BABY_TRIGGER_ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * Getter for {@code evolution_chains.id}.
     */
    public Integer getId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code evolution_chains.id}.
     */
    public void setId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getBabyTriggerItemId();
    }

    /**
     * Getter for {@code evolution_chains.baby_trigger_item_id}.
     */
    public Integer getBabyTriggerItemId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code evolution_chains.baby_trigger_item_id}.
     */
    public void setBabyTriggerItemId(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvolutionChainsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public EvolutionChainsRecord value2(Integer value) {
        setBabyTriggerItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EvolutionChainsRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
