/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.Experience;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class ExperienceRecord extends UpdatableRecordImpl<ExperienceRecord>
        implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 800612323;

    /**
     * Create a detached ExperienceRecord
     */
    public ExperienceRecord() {
        super(Experience.EXPERIENCE);
    }

    /**
     * Create a detached, initialised ExperienceRecord
     */
    public ExperienceRecord(Integer growthRateId, Integer level, Integer experience) {
        super(Experience.EXPERIENCE);

        setValue(0, growthRateId);
        setValue(1, level);
        setValue(2, experience);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Experience.EXPERIENCE.GROWTH_RATE_ID;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Experience.EXPERIENCE.LEVEL;
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Experience.EXPERIENCE.EXPERIENCE_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getGrowthRateId();
    }

    /**
     * Getter for {@code experience.growth_rate_id}.
     */
    public Integer getGrowthRateId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code experience.growth_rate_id}.
     */
    public void setGrowthRateId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLevel();
    }

    /**
     * Getter for {@code experience.level}.
     */
    public Integer getLevel() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code experience.level}.
     */
    public void setLevel(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getExperience();
    }

    /**
     * Getter for {@code experience.experience}.
     */
    public Integer getExperience() {
        return (Integer) getValue(2);
    }

    /**
     * Setter for {@code experience.experience}.
     */
    public void setExperience(Integer value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value1(Integer value) {
        setGrowthRateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value2(Integer value) {
        setLevel(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord value3(Integer value) {
        setExperience(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ExperienceRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
