/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.Generations;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class GenerationsRecord extends UpdatableRecordImpl<GenerationsRecord>
        implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 252171135;

    /**
     * Create a detached GenerationsRecord
     */
    public GenerationsRecord() {
        super(Generations.GENERATIONS);
    }

    /**
     * Create a detached, initialised GenerationsRecord
     */
    public GenerationsRecord(Integer id, Integer mainRegionId, String identifier) {
        super(Generations.GENERATIONS);

        setValue(0, id);
        setValue(1, mainRegionId);
        setValue(2, identifier);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Generations.GENERATIONS.ID;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Generations.GENERATIONS.MAIN_REGION_ID;
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Generations.GENERATIONS.IDENTIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * Getter for {@code generations.id}.
     */
    public Integer getId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code generations.id}.
     */
    public void setId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMainRegionId();
    }

    /**
     * Getter for {@code generations.main_region_id}.
     */
    public Integer getMainRegionId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code generations.main_region_id}.
     */
    public void setMainRegionId(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIdentifier();
    }

    /**
     * Getter for {@code generations.identifier}.
     */
    public String getIdentifier() {
        return (String) getValue(2);
    }

    /**
     * Setter for {@code generations.identifier}.
     */
    public void setIdentifier(String value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenerationsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenerationsRecord value2(Integer value) {
        setMainRegionId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public GenerationsRecord value3(String value) {
        setIdentifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GenerationsRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
