/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.ItemFlagProse;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class ItemFlagProseRecord extends UpdatableRecordImpl<ItemFlagProseRecord>
        implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = -1032021301;

    /**
     * Create a detached ItemFlagProseRecord
     */
    public ItemFlagProseRecord() {
        super(ItemFlagProse.ITEM_FLAG_PROSE);
    }

    /**
     * Create a detached, initialised ItemFlagProseRecord
     */
    public ItemFlagProseRecord(Integer itemFlagId, Integer localLanguageId, String name, String description) {
        super(ItemFlagProse.ITEM_FLAG_PROSE);

        setValue(0, itemFlagId);
        setValue(1, localLanguageId);
        setValue(2, name);
        setValue(3, description);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ItemFlagProse.ITEM_FLAG_PROSE.ITEM_FLAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ItemFlagProse.ITEM_FLAG_PROSE.LOCAL_LANGUAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ItemFlagProse.ITEM_FLAG_PROSE.NAME;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ItemFlagProse.ITEM_FLAG_PROSE.DESCRIPTION;
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getItemFlagId();
    }

    /**
     * Getter for {@code item_flag_prose.item_flag_id}.
     */
    public Integer getItemFlagId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code item_flag_prose.item_flag_id}.
     */
    public void setItemFlagId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLocalLanguageId();
    }

    /**
     * Getter for {@code item_flag_prose.local_language_id}.
     */
    public Integer getLocalLanguageId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code item_flag_prose.local_language_id}.
     */
    public void setLocalLanguageId(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * Getter for {@code item_flag_prose.name}.
     */
    public String getName() {
        return (String) getValue(2);
    }

    /**
     * Setter for {@code item_flag_prose.name}.
     */
    public void setName(String value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * Getter for {@code item_flag_prose.description}.
     */
    public String getDescription() {
        return (String) getValue(3);
    }

    /**
     * Setter for {@code item_flag_prose.description}.
     */
    public void setDescription(String value) {
        setValue(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemFlagProseRecord value1(Integer value) {
        setItemFlagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemFlagProseRecord value2(Integer value) {
        setLocalLanguageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemFlagProseRecord value3(String value) {
        setName(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemFlagProseRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemFlagProseRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
