/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.MoveMetaCategoryProse;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MoveMetaCategoryProseRecord extends UpdatableRecordImpl<MoveMetaCategoryProseRecord>
        implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = -1046003109;

    /**
     * Create a detached MoveMetaCategoryProseRecord
     */
    public MoveMetaCategoryProseRecord() {
        super(MoveMetaCategoryProse.MOVE_META_CATEGORY_PROSE);
    }

    /**
     * Create a detached, initialised MoveMetaCategoryProseRecord
     */
    public MoveMetaCategoryProseRecord(Integer moveMetaCategoryId, Integer localLanguageId, String description) {
        super(MoveMetaCategoryProse.MOVE_META_CATEGORY_PROSE);

        setValue(0, moveMetaCategoryId);
        setValue(1, localLanguageId);
        setValue(2, description);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MoveMetaCategoryProse.MOVE_META_CATEGORY_PROSE.MOVE_META_CATEGORY_ID;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MoveMetaCategoryProse.MOVE_META_CATEGORY_PROSE.LOCAL_LANGUAGE_ID;
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MoveMetaCategoryProse.MOVE_META_CATEGORY_PROSE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMoveMetaCategoryId();
    }

    /**
     * Getter for {@code move_meta_category_prose.move_meta_category_id}.
     */
    public Integer getMoveMetaCategoryId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code move_meta_category_prose.move_meta_category_id}.
     */
    public void setMoveMetaCategoryId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLocalLanguageId();
    }

    /**
     * Getter for {@code move_meta_category_prose.local_language_id}.
     */
    public Integer getLocalLanguageId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code move_meta_category_prose.local_language_id}.
     */
    public void setLocalLanguageId(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * Getter for {@code move_meta_category_prose.description}.
     */
    public String getDescription() {
        return (String) getValue(2);
    }

    /**
     * Setter for {@code move_meta_category_prose.description}.
     */
    public void setDescription(String value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaCategoryProseRecord value1(Integer value) {
        setMoveMetaCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaCategoryProseRecord value2(Integer value) {
        setLocalLanguageId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaCategoryProseRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaCategoryProseRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
