/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.Moves;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MovesRecord extends UpdatableRecordImpl<MovesRecord> implements Record15<Integer, String, Integer, Integer, Short, Short, Short, Short, Integer, Integer, Integer, Integer,
                Integer, Integer, Integer> {

    private static final long serialVersionUID = 1591473234;

    /**
     * Create a detached MovesRecord
     */
    public MovesRecord() {
        super(Moves.MOVES);
    }

    /**
     * Create a detached, initialised MovesRecord
     */
    public MovesRecord(Integer id, String identifier, Integer generationId, Integer typeId, Short power, Short pp,
                       Short accuracy, Short priority, Integer targetId, Integer damageClassId, Integer effectId,
                       Integer effectChance, Integer contestTypeId, Integer contestEffectId,
                       Integer superContestEffectId) {
        super(Moves.MOVES);

        setValue(0, id);
        setValue(1, identifier);
        setValue(2, generationId);
        setValue(3, typeId);
        setValue(4, power);
        setValue(5, pp);
        setValue(6, accuracy);
        setValue(7, priority);
        setValue(8, targetId);
        setValue(9, damageClassId);
        setValue(10, effectId);
        setValue(11, effectChance);
        setValue(12, contestTypeId);
        setValue(13, contestEffectId);
        setValue(14, superContestEffectId);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, Integer, Integer, Short, Short, Short, Short, Integer, Integer, Integer, Integer,
            Integer, Integer, Integer> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, Integer, Integer, Short, Short, Short, Short, Integer, Integer, Integer, Integer,
            Integer, Integer, Integer> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Moves.MOVES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Moves.MOVES.IDENTIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Moves.MOVES.GENERATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Moves.MOVES.TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return Moves.MOVES.POWER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return Moves.MOVES.PP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return Moves.MOVES.ACCURACY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field8() {
        return Moves.MOVES.PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Moves.MOVES.TARGET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Moves.MOVES.DAMAGE_CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Moves.MOVES.EFFECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Moves.MOVES.EFFECT_CHANCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Moves.MOVES.CONTEST_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Moves.MOVES.CONTEST_EFFECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return Moves.MOVES.SUPER_CONTEST_EFFECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * Getter for {@code moves.id}.
     */
    public Integer getId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code moves.id}.
     */
    public void setId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIdentifier();
    }

    /**
     * Getter for {@code moves.identifier}.
     */
    public String getIdentifier() {
        return (String) getValue(1);
    }

    /**
     * Setter for {@code moves.identifier}.
     */
    public void setIdentifier(String value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGenerationId();
    }

    /**
     * Getter for {@code moves.generation_id}.
     */
    public Integer getGenerationId() {
        return (Integer) getValue(2);
    }

    /**
     * Setter for {@code moves.generation_id}.
     */
    public void setGenerationId(Integer value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTypeId();
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for {@code moves.type_id}.
     */
    public Integer getTypeId() {
        return (Integer) getValue(3);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for {@code moves.type_id}.
     */
    public void setTypeId(Integer value) {
        setValue(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getPower();
    }

    /**
     * Getter for {@code moves.power}.
     */
    public Short getPower() {
        return (Short) getValue(4);
    }

    /**
     * Setter for {@code moves.power}.
     */
    public void setPower(Short value) {
        setValue(4, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getPp();
    }

    /**
     * Getter for {@code moves.pp}.
     */
    public Short getPp() {
        return (Short) getValue(5);
    }

    /**
     * Setter for {@code moves.pp}.
     */
    public void setPp(Short value) {
        setValue(5, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getAccuracy();
    }

    /**
     * Getter for {@code moves.accuracy}.
     */
    public Short getAccuracy() {
        return (Short) getValue(6);
    }

    /**
     * Setter for {@code moves.accuracy}.
     */
    public void setAccuracy(Short value) {
        setValue(6, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value8() {
        return getPriority();
    }

    /**
     * Getter for {@code moves.priority}.
     */
    public Short getPriority() {
        return (Short) getValue(7);
    }

    /**
     * Setter for {@code moves.priority}.
     */
    public void setPriority(Short value) {
        setValue(7, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getTargetId();
    }

    /**
     * Getter for {@code moves.target_id}.
     */
    public Integer getTargetId() {
        return (Integer) getValue(8);
    }

    /**
     * Setter for {@code moves.target_id}.
     */
    public void setTargetId(Integer value) {
        setValue(8, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getDamageClassId();
    }

    /**
     * Getter for {@code moves.damage_class_id}.
     */
    public Integer getDamageClassId() {
        return (Integer) getValue(9);
    }

    /**
     * Setter for {@code moves.damage_class_id}.
     */
    public void setDamageClassId(Integer value) {
        setValue(9, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getEffectId();
    }

    /**
     * Getter for {@code moves.effect_id}.
     */
    public Integer getEffectId() {
        return (Integer) getValue(10);
    }

    /**
     * Setter for {@code moves.effect_id}.
     */
    public void setEffectId(Integer value) {
        setValue(10, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getEffectChance();
    }

    /**
     * Getter for {@code moves.effect_chance}.
     */
    public Integer getEffectChance() {
        return (Integer) getValue(11);
    }

    /**
     * Setter for {@code moves.effect_chance}.
     */
    public void setEffectChance(Integer value) {
        setValue(11, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getContestTypeId();
    }

    /**
     * Getter for {@code moves.contest_type_id}.
     */
    public Integer getContestTypeId() {
        return (Integer) getValue(12);
    }

    /**
     * Setter for {@code moves.contest_type_id}.
     */
    public void setContestTypeId(Integer value) {
        setValue(12, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getContestEffectId();
    }

    /**
     * Getter for {@code moves.contest_effect_id}.
     */
    public Integer getContestEffectId() {
        return (Integer) getValue(13);
    }

    /**
     * Setter for {@code moves.contest_effect_id}.
     */
    public void setContestEffectId(Integer value) {
        setValue(13, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getSuperContestEffectId();
    }

    /**
     * Getter for {@code moves.super_contest_effect_id}.
     */
    public Integer getSuperContestEffectId() {
        return (Integer) getValue(14);
    }

    /**
     * Setter for {@code moves.super_contest_effect_id}.
     */
    public void setSuperContestEffectId(Integer value) {
        setValue(14, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value2(String value) {
        setIdentifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value3(Integer value) {
        setGenerationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value4(Integer value) {
        setTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value5(Short value) {
        setPower(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value6(Short value) {
        setPp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value7(Short value) {
        setAccuracy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value8(Short value) {
        setPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value9(Integer value) {
        setTargetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value10(Integer value) {
        setDamageClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value11(Integer value) {
        setEffectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value12(Integer value) {
        setEffectChance(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value13(Integer value) {
        setContestTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value14(Integer value) {
        setContestEffectId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord value15(Integer value) {
        setSuperContestEffectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MovesRecord values(Integer value1, String value2, Integer value3, Integer value4, Short value5, Short value6,
                              Short value7, Short value8, Integer value9, Integer value10, Integer value11,
                              Integer value12, Integer value13, Integer value14, Integer value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }
}
