/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.MoveMetaStatChanges;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MoveMetaStatChangesRecord extends UpdatableRecordImpl<MoveMetaStatChangesRecord>
        implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -789287721;

    /**
     * Create a detached MoveMetaStatChangesRecord
     */
    public MoveMetaStatChangesRecord() {
        super(MoveMetaStatChanges.MOVE_META_STAT_CHANGES);
    }

    /**
     * Create a detached, initialised MoveMetaStatChangesRecord
     */
    public MoveMetaStatChangesRecord(Integer moveId, Integer statId, Integer change) {
        super(MoveMetaStatChanges.MOVE_META_STAT_CHANGES);

        setValue(0, moveId);
        setValue(1, statId);
        setValue(2, change);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MoveMetaStatChanges.MOVE_META_STAT_CHANGES.MOVE_ID;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MoveMetaStatChanges.MOVE_META_STAT_CHANGES.STAT_ID;
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MoveMetaStatChanges.MOVE_META_STAT_CHANGES.CHANGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMoveId();
    }

    /**
     * Getter for {@code move_meta_stat_changes.move_id}.
     */
    public Integer getMoveId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code move_meta_stat_changes.move_id}.
     */
    public void setMoveId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStatId();
    }

    /**
     * Getter for {@code move_meta_stat_changes.stat_id}.
     */
    public Integer getStatId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code move_meta_stat_changes.stat_id}.
     */
    public void setStatId(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getChange();
    }

    /**
     * Getter for {@code move_meta_stat_changes.change}.
     */
    public Integer getChange() {
        return (Integer) getValue(2);
    }

    /**
     * Setter for {@code move_meta_stat_changes.change}.
     */
    public void setChange(Integer value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaStatChangesRecord value1(Integer value) {
        setMoveId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaStatChangesRecord value2(Integer value) {
        setStatId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaStatChangesRecord value3(Integer value) {
        setChange(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaStatChangesRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
