/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.MoveMetaAilmentNames;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class MoveMetaAilmentNamesRecord extends UpdatableRecordImpl<MoveMetaAilmentNamesRecord>
        implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 445592839;

    /**
     * Create a detached MoveMetaAilmentNamesRecord
     */
    public MoveMetaAilmentNamesRecord() {
        super(MoveMetaAilmentNames.MOVE_META_AILMENT_NAMES);
    }

    /**
     * Create a detached, initialised MoveMetaAilmentNamesRecord
     */
    public MoveMetaAilmentNamesRecord(Integer moveMetaAilmentId, Integer localLanguageId, String name) {
        super(MoveMetaAilmentNames.MOVE_META_AILMENT_NAMES);

        setValue(0, moveMetaAilmentId);
        setValue(1, localLanguageId);
        setValue(2, name);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MoveMetaAilmentNames.MOVE_META_AILMENT_NAMES.MOVE_META_AILMENT_ID;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MoveMetaAilmentNames.MOVE_META_AILMENT_NAMES.LOCAL_LANGUAGE_ID;
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MoveMetaAilmentNames.MOVE_META_AILMENT_NAMES.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMoveMetaAilmentId();
    }

    /**
     * Getter for {@code move_meta_ailment_names.move_meta_ailment_id}.
     */
    public Integer getMoveMetaAilmentId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code move_meta_ailment_names.move_meta_ailment_id}.
     */
    public void setMoveMetaAilmentId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLocalLanguageId();
    }

    /**
     * Getter for {@code move_meta_ailment_names.local_language_id}.
     */
    public Integer getLocalLanguageId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code move_meta_ailment_names.local_language_id}.
     */
    public void setLocalLanguageId(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * Getter for {@code move_meta_ailment_names.name}.
     */
    public String getName() {
        return (String) getValue(2);
    }

    /**
     * Setter for {@code move_meta_ailment_names.name}.
     */
    public void setName(String value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaAilmentNamesRecord value1(Integer value) {
        setMoveMetaAilmentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaAilmentNamesRecord value2(Integer value) {
        setLocalLanguageId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaAilmentNamesRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoveMetaAilmentNamesRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
