/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.Pokemon;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class PokemonRecord extends UpdatableRecordImpl<PokemonRecord>
        implements Record8<Integer, String, Integer, Integer, Integer, Integer, Integer, Boolean> {

    private static final long serialVersionUID = 1029495550;

    /**
     * Create a detached PokemonRecord
     */
    public PokemonRecord() {
        super(Pokemon.POKEMON);
    }

    /**
     * Create a detached, initialised PokemonRecord
     */
    public PokemonRecord(Integer id, String identifier, Integer speciesId, Integer height, Integer weight,
                         Integer baseExperience, Integer speciesOrder, Boolean isDefault) {
        super(Pokemon.POKEMON);

        setValue(0, id);
        setValue(1, identifier);
        setValue(2, speciesId);
        setValue(3, height);
        setValue(4, weight);
        setValue(5, baseExperience);
        setValue(6, speciesOrder);
        setValue(7, isDefault);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, Integer, Integer, Integer, Integer, Boolean> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, Integer, Integer, Integer, Integer, Boolean> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Pokemon.POKEMON.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Pokemon.POKEMON.IDENTIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Pokemon.POKEMON.SPECIES_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Pokemon.POKEMON.HEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Pokemon.POKEMON.WEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Pokemon.POKEMON.BASE_EXPERIENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Pokemon.POKEMON.SPECIES_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Pokemon.POKEMON.IS_DEFAULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * Getter for {@code pokemon.id}.
     */
    public Integer getId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code pokemon.id}.
     */
    public void setId(Integer value) {
        setValue(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIdentifier();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for {@code pokemon.identifier}.
     */
    public String getIdentifier() {
        return (String) getValue(1);
    }

    /**
     * Setter for {@code pokemon.identifier}.
     */
    public void setIdentifier(String value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSpeciesId();
    }

    /**
     * Getter for {@code pokemon.species_id}.
     */
    public Integer getSpeciesId() {
        return (Integer) getValue(2);
    }

    /**
     * Setter for {@code pokemon.species_id}.
     */
    public void setSpeciesId(Integer value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getHeight();
    }

    /**
     * Getter for {@code pokemon.height}.
     */
    public Integer getHeight() {
        return (Integer) getValue(3);
    }

    /**
     * Setter for {@code pokemon.height}.
     */
    public void setHeight(Integer value) {
        setValue(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getWeight();
    }

    /**
     * Getter for {@code pokemon.weight}.
     */
    public Integer getWeight() {
        return (Integer) getValue(4);
    }

    /**
     * Setter for {@code pokemon.weight}.
     */
    public void setWeight(Integer value) {
        setValue(4, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getBaseExperience();
    }

    /**
     * Getter for {@code pokemon.base_experience}.
     */
    public Integer getBaseExperience() {
        return (Integer) getValue(5);
    }

    /**
     * Setter for {@code pokemon.base_experience}.
     */
    public void setBaseExperience(Integer value) {
        setValue(5, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getSpeciesOrder();
    }

    /**
     * Getter for {@code pokemon.species_order}.
     */
    public Integer getSpeciesOrder() {
        return (Integer) getValue(6);
    }

    /**
     * Setter for {@code pokemon.species_order}.
     */
    public void setSpeciesOrder(Integer value) {
        setValue(6, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getIsDefault();
    }

    /**
     * Getter for {@code pokemon.is_default}.
     */
    public Boolean getIsDefault() {
        return (Boolean) getValue(7);
    }

    /**
     * Setter for {@code pokemon.is_default}.
     */
    public void setIsDefault(Boolean value) {
        setValue(7, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonRecord value2(String value) {
        setIdentifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonRecord value3(Integer value) {
        setSpeciesId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonRecord value4(Integer value) {
        setHeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonRecord value5(Integer value) {
        setWeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonRecord value6(Integer value) {
        setBaseExperience(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonRecord value7(Integer value) {
        setSpeciesOrder(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonRecord value8(Boolean value) {
        setIsDefault(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5,
                                Integer value6, Integer value7, Boolean value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }
}
