/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.PokemonStats;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class PokemonStatsRecord extends UpdatableRecordImpl<PokemonStatsRecord>
        implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 578540447;

    /**
     * Create a detached PokemonStatsRecord
     */
    public PokemonStatsRecord() {
        super(PokemonStats.POKEMON_STATS);
    }

    /**
     * Create a detached, initialised PokemonStatsRecord
     */
    public PokemonStatsRecord(Integer pokemonId, Integer statId, Integer baseStat, Integer effort) {
        super(PokemonStats.POKEMON_STATS);

        setValue(0, pokemonId);
        setValue(1, statId);
        setValue(2, baseStat);
        setValue(3, effort);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PokemonStats.POKEMON_STATS.POKEMON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PokemonStats.POKEMON_STATS.STAT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PokemonStats.POKEMON_STATS.BASE_STAT;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PokemonStats.POKEMON_STATS.EFFORT;
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPokemonId();
    }

    /**
     * Getter for {@code pokemon_stats.pokemon_id}.
     */
    public Integer getPokemonId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code pokemon_stats.pokemon_id}.
     */
    public void setPokemonId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStatId();
    }

    /**
     * Getter for {@code pokemon_stats.stat_id}.
     */
    public Integer getStatId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code pokemon_stats.stat_id}.
     */
    public void setStatId(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getBaseStat();
    }

    /**
     * Getter for {@code pokemon_stats.base_stat}.
     */
    public Integer getBaseStat() {
        return (Integer) getValue(2);
    }

    /**
     * Setter for {@code pokemon_stats.base_stat}.
     */
    public void setBaseStat(Integer value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getEffort();
    }

    /**
     * Getter for {@code pokemon_stats.effort}.
     */
    public Integer getEffort() {
        return (Integer) getValue(3);
    }

    /**
     * Setter for {@code pokemon_stats.effort}.
     */
    public void setEffort(Integer value) {
        setValue(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonStatsRecord value1(Integer value) {
        setPokemonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonStatsRecord value2(Integer value) {
        setStatId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonStatsRecord value3(Integer value) {
        setBaseStat(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonStatsRecord value4(Integer value) {
        setEffort(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonStatsRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
