/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.PokemonFormNames;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class PokemonFormNamesRecord extends UpdatableRecordImpl<PokemonFormNamesRecord>
        implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = 384436505;

    /**
     * Create a detached PokemonFormNamesRecord
     */
    public PokemonFormNamesRecord() {
        super(PokemonFormNames.POKEMON_FORM_NAMES);
    }

    /**
     * Create a detached, initialised PokemonFormNamesRecord
     */
    public PokemonFormNamesRecord(Integer pokemonFormId, Integer localLanguageId, String formName, String pokemonName) {
        super(PokemonFormNames.POKEMON_FORM_NAMES);

        setValue(0, pokemonFormId);
        setValue(1, localLanguageId);
        setValue(2, formName);
        setValue(3, pokemonName);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PokemonFormNames.POKEMON_FORM_NAMES.POKEMON_FORM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PokemonFormNames.POKEMON_FORM_NAMES.LOCAL_LANGUAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PokemonFormNames.POKEMON_FORM_NAMES.FORM_NAME;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PokemonFormNames.POKEMON_FORM_NAMES.POKEMON_NAME;
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPokemonFormId();
    }

    /**
     * Getter for {@code pokemon_form_names.pokemon_form_id}.
     */
    public Integer getPokemonFormId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code pokemon_form_names.pokemon_form_id}.
     */
    public void setPokemonFormId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLocalLanguageId();
    }

    /**
     * Getter for {@code pokemon_form_names.local_language_id}.
     */
    public Integer getLocalLanguageId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code pokemon_form_names.local_language_id}.
     */
    public void setLocalLanguageId(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getFormName();
    }

    /**
     * Getter for {@code pokemon_form_names.form_name}.
     */
    public String getFormName() {
        return (String) getValue(2);
    }

    /**
     * Setter for {@code pokemon_form_names.form_name}.
     */
    public void setFormName(String value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPokemonName();
    }

    /**
     * Getter for {@code pokemon_form_names.pokemon_name}.
     */
    public String getPokemonName() {
        return (String) getValue(3);
    }

    /**
     * Setter for {@code pokemon_form_names.pokemon_name}.
     */
    public void setPokemonName(String value) {
        setValue(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonFormNamesRecord value1(Integer value) {
        setPokemonFormId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonFormNamesRecord value2(Integer value) {
        setLocalLanguageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonFormNamesRecord value3(String value) {
        setFormName(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonFormNamesRecord value4(String value) {
        setPokemonName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonFormNamesRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
