/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.PokemonSpecies;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class PokemonSpeciesRecord extends UpdatableRecordImpl<PokemonSpeciesRecord> implements Record18<Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer,
                Boolean, Integer, Boolean, Integer, Boolean, Integer, Integer> {

    private static final long serialVersionUID = -1183080835;

    /**
     * Create a detached PokemonSpeciesRecord
     */
    public PokemonSpeciesRecord() {
        super(PokemonSpecies.POKEMON_SPECIES);
    }

    /**
     * Create a detached, initialised PokemonSpeciesRecord
     */
    public PokemonSpeciesRecord(Integer id, String identifier, Integer generationId, Integer evolvesFromSpeciesId,
                                Integer evolutionChainId, Integer colorId, Integer shapeId, Integer habitatId,
                                Integer genderRate, Integer captureRate, Integer baseHappiness, Boolean isBaby,
                                Integer hatchCounter, Boolean hasGenderDifferences, Integer growthRateId,
                                Boolean formsSwitchable, Integer order, Integer conquestOrder) {
        super(PokemonSpecies.POKEMON_SPECIES);

        setValue(0, id);
        setValue(1, identifier);
        setValue(2, generationId);
        setValue(3, evolvesFromSpeciesId);
        setValue(4, evolutionChainId);
        setValue(5, colorId);
        setValue(6, shapeId);
        setValue(7, habitatId);
        setValue(8, genderRate);
        setValue(9, captureRate);
        setValue(10, baseHappiness);
        setValue(11, isBaby);
        setValue(12, hatchCounter);
        setValue(13, hasGenderDifferences);
        setValue(14, growthRateId);
        setValue(15, formsSwitchable);
        setValue(16, order);
        setValue(17, conquestOrder);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer,
            Boolean, Integer, Boolean, Integer, Boolean, Integer, Integer> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<Integer, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer,
            Boolean, Integer, Boolean, Integer, Boolean, Integer, Integer> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PokemonSpecies.POKEMON_SPECIES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PokemonSpecies.POKEMON_SPECIES.IDENTIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PokemonSpecies.POKEMON_SPECIES.GENERATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PokemonSpecies.POKEMON_SPECIES.EVOLVES_FROM_SPECIES_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return PokemonSpecies.POKEMON_SPECIES.EVOLUTION_CHAIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return PokemonSpecies.POKEMON_SPECIES.COLOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return PokemonSpecies.POKEMON_SPECIES.SHAPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return PokemonSpecies.POKEMON_SPECIES.HABITAT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return PokemonSpecies.POKEMON_SPECIES.GENDER_RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return PokemonSpecies.POKEMON_SPECIES.CAPTURE_RATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return PokemonSpecies.POKEMON_SPECIES.BASE_HAPPINESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return PokemonSpecies.POKEMON_SPECIES.IS_BABY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return PokemonSpecies.POKEMON_SPECIES.HATCH_COUNTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return PokemonSpecies.POKEMON_SPECIES.HAS_GENDER_DIFFERENCES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return PokemonSpecies.POKEMON_SPECIES.GROWTH_RATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field16() {
        return PokemonSpecies.POKEMON_SPECIES.FORMS_SWITCHABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return PokemonSpecies.POKEMON_SPECIES.ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field18() {
        return PokemonSpecies.POKEMON_SPECIES.CONQUEST_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * Getter for {@code pokemon_species.id}.
     */
    public Integer getId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code pokemon_species.id}.
     */
    public void setId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getIdentifier();
    }

    /**
     * Getter for {@code pokemon_species.identifier}.
     */
    public String getIdentifier() {
        return (String) getValue(1);
    }

    /**
     * Setter for {@code pokemon_species.identifier}.
     */
    public void setIdentifier(String value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGenerationId();
    }

    /**
     * Getter for {@code pokemon_species.generation_id}.
     */
    public Integer getGenerationId() {
        return (Integer) getValue(2);
    }

    /**
     * Setter for {@code pokemon_species.generation_id}.
     */
    public void setGenerationId(Integer value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getEvolvesFromSpeciesId();
    }

    /**
     * Getter for {@code pokemon_species.evolves_from_species_id}.
     */
    public Integer getEvolvesFromSpeciesId() {
        return (Integer) getValue(3);
    }

    /**
     * Setter for {@code pokemon_species.evolves_from_species_id}.
     */
    public void setEvolvesFromSpeciesId(Integer value) {
        setValue(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getEvolutionChainId();
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for {@code pokemon_species.evolution_chain_id}.
     */
    public Integer getEvolutionChainId() {
        return (Integer) getValue(4);
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for {@code pokemon_species.evolution_chain_id}.
     */
    public void setEvolutionChainId(Integer value) {
        setValue(4, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getColorId();
    }

    /**
     * Getter for {@code pokemon_species.color_id}.
     */
    public Integer getColorId() {
        return (Integer) getValue(5);
    }

    /**
     * Setter for {@code pokemon_species.color_id}.
     */
    public void setColorId(Integer value) {
        setValue(5, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getShapeId();
    }

    /**
     * Getter for {@code pokemon_species.shape_id}.
     */
    public Integer getShapeId() {
        return (Integer) getValue(6);
    }

    /**
     * Setter for {@code pokemon_species.shape_id}.
     */
    public void setShapeId(Integer value) {
        setValue(6, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getHabitatId();
    }

    /**
     * Getter for {@code pokemon_species.habitat_id}.
     */
    public Integer getHabitatId() {
        return (Integer) getValue(7);
    }

    /**
     * Setter for {@code pokemon_species.habitat_id}.
     */
    public void setHabitatId(Integer value) {
        setValue(7, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getGenderRate();
    }

    /**
     * Getter for {@code pokemon_species.gender_rate}.
     */
    public Integer getGenderRate() {
        return (Integer) getValue(8);
    }

    /**
     * Setter for {@code pokemon_species.gender_rate}.
     */
    public void setGenderRate(Integer value) {
        setValue(8, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getCaptureRate();
    }

    /**
     * Getter for {@code pokemon_species.capture_rate}.
     */
    public Integer getCaptureRate() {
        return (Integer) getValue(9);
    }

    /**
     * Setter for {@code pokemon_species.capture_rate}.
     */
    public void setCaptureRate(Integer value) {
        setValue(9, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getBaseHappiness();
    }

    /**
     * Getter for {@code pokemon_species.base_happiness}.
     */
    public Integer getBaseHappiness() {
        return (Integer) getValue(10);
    }

    /**
     * Setter for {@code pokemon_species.base_happiness}.
     */
    public void setBaseHappiness(Integer value) {
        setValue(10, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getIsBaby();
    }

    /**
     * Getter for {@code pokemon_species.is_baby}.
     */
    public Boolean getIsBaby() {
        return (Boolean) getValue(11);
    }

    /**
     * Setter for {@code pokemon_species.is_baby}.
     */
    public void setIsBaby(Boolean value) {
        setValue(11, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getHatchCounter();
    }

    /**
     * Getter for {@code pokemon_species.hatch_counter}.
     */
    public Integer getHatchCounter() {
        return (Integer) getValue(12);
    }

    /**
     * Setter for {@code pokemon_species.hatch_counter}.
     */
    public void setHatchCounter(Integer value) {
        setValue(12, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getHasGenderDifferences();
    }

    /**
     * Getter for {@code pokemon_species.has_gender_differences}.
     */
    public Boolean getHasGenderDifferences() {
        return (Boolean) getValue(13);
    }

    /**
     * Setter for {@code pokemon_species.has_gender_differences}.
     */
    public void setHasGenderDifferences(Boolean value) {
        setValue(13, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getGrowthRateId();
    }

    /**
     * Getter for {@code pokemon_species.growth_rate_id}.
     */
    public Integer getGrowthRateId() {
        return (Integer) getValue(14);
    }

    /**
     * Setter for {@code pokemon_species.growth_rate_id}.
     */
    public void setGrowthRateId(Integer value) {
        setValue(14, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value16() {
        return getFormsSwitchable();
    }

    /**
     * Getter for {@code pokemon_species.forms_switchable}.
     */
    public Boolean getFormsSwitchable() {
        return (Boolean) getValue(15);
    }

    /**
     * Setter for {@code pokemon_species.forms_switchable}.
     */
    public void setFormsSwitchable(Boolean value) {
        setValue(15, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getOrder();
    }

    /**
     * Getter for {@code pokemon_species.order}.
     */
    public Integer getOrder() {
        return (Integer) getValue(16);
    }

    /**
     * Setter for {@code pokemon_species.order}.
     */
    public void setOrder(Integer value) {
        setValue(16, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value18() {
        return getConquestOrder();
    }

    /**
     * Getter for {@code pokemon_species.conquest_order}.
     */
    public Integer getConquestOrder() {
        return (Integer) getValue(17);
    }

    /**
     * Setter for {@code pokemon_species.conquest_order}.
     */
    public void setConquestOrder(Integer value) {
        setValue(17, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value2(String value) {
        setIdentifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value3(Integer value) {
        setGenerationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value4(Integer value) {
        setEvolvesFromSpeciesId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value5(Integer value) {
        setEvolutionChainId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value6(Integer value) {
        setColorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value7(Integer value) {
        setShapeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value8(Integer value) {
        setHabitatId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value9(Integer value) {
        setGenderRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value10(Integer value) {
        setCaptureRate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value11(Integer value) {
        setBaseHappiness(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value12(Boolean value) {
        setIsBaby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value13(Integer value) {
        setHatchCounter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value14(Boolean value) {
        setHasGenderDifferences(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value15(Integer value) {
        setGrowthRateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value16(Boolean value) {
        setFormsSwitchable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value17(Integer value) {
        setOrder(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord value18(Integer value) {
        setConquestOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonSpeciesRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5,
                                       Integer value6, Integer value7, Integer value8, Integer value9, Integer value10,
                                       Integer value11, Boolean value12, Integer value13, Boolean value14,
                                       Integer value15, Boolean value16, Integer value17, Integer value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }
}
