/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.PokemonAbilities;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class PokemonAbilitiesRecord extends UpdatableRecordImpl<PokemonAbilitiesRecord>
        implements Record4<Integer, Integer, Boolean, Integer> {

    private static final long serialVersionUID = 1644115632;

    /**
     * Create a detached PokemonAbilitiesRecord
     */
    public PokemonAbilitiesRecord() {
        super(PokemonAbilities.POKEMON_ABILITIES);
    }

    /**
     * Create a detached, initialised PokemonAbilitiesRecord
     */
    public PokemonAbilitiesRecord(Integer pokemonId, Integer abilityId, Boolean isHidden, Integer slot) {
        super(PokemonAbilities.POKEMON_ABILITIES);

        setValue(0, pokemonId);
        setValue(1, abilityId);
        setValue(2, isHidden);
        setValue(3, slot);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Boolean, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Boolean, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PokemonAbilities.POKEMON_ABILITIES.POKEMON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PokemonAbilities.POKEMON_ABILITIES.ABILITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field3() {
        return PokemonAbilities.POKEMON_ABILITIES.IS_HIDDEN;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PokemonAbilities.POKEMON_ABILITIES.SLOT;
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPokemonId();
    }

    /**
     * Getter for {@code pokemon_abilities.pokemon_id}.
     */
    public Integer getPokemonId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code pokemon_abilities.pokemon_id}.
     */
    public void setPokemonId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAbilityId();
    }

    /**
     * Getter for {@code pokemon_abilities.ability_id}.
     */
    public Integer getAbilityId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code pokemon_abilities.ability_id}.
     */
    public void setAbilityId(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value3() {
        return getIsHidden();
    }

    /**
     * Getter for {@code pokemon_abilities.is_hidden}.
     */
    public Boolean getIsHidden() {
        return (Boolean) getValue(2);
    }

    /**
     * Setter for {@code pokemon_abilities.is_hidden}.
     */
    public void setIsHidden(Boolean value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSlot();
    }

    /**
     * Getter for {@code pokemon_abilities.slot}.
     */
    public Integer getSlot() {
        return (Integer) getValue(3);
    }

    /**
     * Setter for {@code pokemon_abilities.slot}.
     */
    public void setSlot(Integer value) {
        setValue(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonAbilitiesRecord value1(Integer value) {
        setPokemonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonAbilitiesRecord value2(Integer value) {
        setAbilityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonAbilitiesRecord value3(Boolean value) {
        setIsHidden(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonAbilitiesRecord value4(Integer value) {
        setSlot(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PokemonAbilitiesRecord values(Integer value1, Integer value2, Boolean value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }
}
