/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.StatHintNames;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class StatHintNamesRecord extends UpdatableRecordImpl<StatHintNamesRecord>
        implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 291818693;

    /**
     * Create a detached StatHintNamesRecord
     */
    public StatHintNamesRecord() {
        super(StatHintNames.STAT_HINT_NAMES);
    }

    /**
     * Create a detached, initialised StatHintNamesRecord
     */
    public StatHintNamesRecord(Integer statHintId, Integer localLanguageId, String message) {
        super(StatHintNames.STAT_HINT_NAMES);

        setValue(0, statHintId);
        setValue(1, localLanguageId);
        setValue(2, message);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return StatHintNames.STAT_HINT_NAMES.STAT_HINT_ID;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return StatHintNames.STAT_HINT_NAMES.LOCAL_LANGUAGE_ID;
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return StatHintNames.STAT_HINT_NAMES.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getStatHintId();
    }

    /**
     * Getter for {@code stat_hint_names.stat_hint_id}.
     */
    public Integer getStatHintId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code stat_hint_names.stat_hint_id}.
     */
    public void setStatHintId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getLocalLanguageId();
    }

    /**
     * Getter for {@code stat_hint_names.local_language_id}.
     */
    public Integer getLocalLanguageId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code stat_hint_names.local_language_id}.
     */
    public void setLocalLanguageId(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMessage();
    }

    /**
     * Getter for {@code stat_hint_names.message}.
     */
    public String getMessage() {
        return (String) getValue(2);
    }

    /**
     * Setter for {@code stat_hint_names.message}.
     */
    public void setMessage(String value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatHintNamesRecord value1(Integer value) {
        setStatHintId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatHintNamesRecord value2(Integer value) {
        setLocalLanguageId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public StatHintNamesRecord value3(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatHintNamesRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
