/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.Stats;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class StatsRecord extends UpdatableRecordImpl<StatsRecord>
        implements Record5<Integer, Integer, String, Boolean, Integer> {

    private static final long serialVersionUID = 1110443125;

    /**
     * Create a detached StatsRecord
     */
    public StatsRecord() {
        super(Stats.STATS);
    }

    /**
     * Create a detached, initialised StatsRecord
     */
    public StatsRecord(Integer id, Integer damageClassId, String identifier, Boolean isBattleOnly, Integer gameIndex) {
        super(Stats.STATS);

        setValue(0, id);
        setValue(1, damageClassId);
        setValue(2, identifier);
        setValue(3, isBattleOnly);
        setValue(4, gameIndex);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Boolean, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, Boolean, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Stats.STATS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Stats.STATS.DAMAGE_CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Stats.STATS.IDENTIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Stats.STATS.IS_BATTLE_ONLY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Stats.STATS.GAME_INDEX;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * Getter for {@code stats.id}.
     */
    public Integer getId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code stats.id}.
     */
    public void setId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDamageClassId();
    }

    /**
     * Getter for {@code stats.damage_class_id}.
     */
    public Integer getDamageClassId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code stats.damage_class_id}.
     */
    public void setDamageClassId(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getIdentifier();
    }

    /**
     * Getter for {@code stats.identifier}.
     */
    public String getIdentifier() {
        return (String) getValue(2);
    }

    /**
     * Setter for {@code stats.identifier}.
     */
    public void setIdentifier(String value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsBattleOnly();
    }

    /**
     * Getter for {@code stats.is_battle_only}.
     */
    public Boolean getIsBattleOnly() {
        return (Boolean) getValue(3);
    }

    /**
     * Setter for {@code stats.is_battle_only}.
     */
    public void setIsBattleOnly(Boolean value) {
        setValue(3, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGameIndex();
    }

    /**
     * Getter for {@code stats.game_index}.
     */
    public Integer getGameIndex() {
        return (Integer) getValue(4);
    }

    /**
     * Setter for {@code stats.game_index}.
     */
    public void setGameIndex(Integer value) {
        setValue(4, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsRecord value2(Integer value) {
        setDamageClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsRecord value3(String value) {
        setIdentifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsRecord value4(Boolean value) {
        setIsBattleOnly(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsRecord value5(Integer value) {
        setGameIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StatsRecord values(Integer value1, Integer value2, String value3, Boolean value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }
}
