/**
 * This class is generated by jOOQ
 */
package com.com.ivbot.sql.schema.tables.records;

import com.com.ivbot.sql.schema.tables.TypeGameIndices;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;

/**
 * This class is generated by jOOQ.
 */
@Generated (
        value = {
                "http://www.jooq.org", "jOOQ version:3.6.2"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class TypeGameIndicesRecord extends UpdatableRecordImpl<TypeGameIndicesRecord>
        implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1216579754;

    /**
     * Create a detached TypeGameIndicesRecord
     */
    public TypeGameIndicesRecord() {
        super(TypeGameIndices.TYPE_GAME_INDICES);
    }

    /**
     * Create a detached, initialised TypeGameIndicesRecord
     */
    public TypeGameIndicesRecord(Integer typeId, Integer generationId, Integer gameIndex) {
        super(TypeGameIndices.TYPE_GAME_INDICES);

        setValue(0, typeId);
        setValue(1, generationId);
        setValue(2, gameIndex);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TypeGameIndices.TYPE_GAME_INDICES.TYPE_ID;
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TypeGameIndices.TYPE_GAME_INDICES.GENERATION_ID;
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TypeGameIndices.TYPE_GAME_INDICES.GAME_INDEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getTypeId();
    }

    /**
     * Getter for {@code type_game_indices.type_id}.
     */
    public Integer getTypeId() {
        return (Integer) getValue(0);
    }

    /**
     * Setter for {@code type_game_indices.type_id}.
     */
    public void setTypeId(Integer value) {
        setValue(0, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getGenerationId();
    }

    /**
     * Getter for {@code type_game_indices.generation_id}.
     */
    public Integer getGenerationId() {
        return (Integer) getValue(1);
    }

    /**
     * Setter for {@code type_game_indices.generation_id}.
     */
    public void setGenerationId(Integer value) {
        setValue(1, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGameIndex();
    }

    /**
     * Getter for {@code type_game_indices.game_index}.
     */
    public Integer getGameIndex() {
        return (Integer) getValue(2);
    }

    /**
     * Setter for {@code type_game_indices.game_index}.
     */
    public void setGameIndex(Integer value) {
        setValue(2, value);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeGameIndicesRecord value1(Integer value) {
        setTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeGameIndicesRecord value2(Integer value) {
        setGenerationId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeGameIndicesRecord value3(Integer value) {
        setGameIndex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeGameIndicesRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }
}
